/*
 * Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#define     DQSGRP_OFFCAL_CR                 0x000
#define     DQSGRP_OFFCAL_CR1                0x004
#define     DQSGRP_OFFCAL_DR                 0x008
#define     DQSGRP_OFFCAL_DR1                0x00c
#define     DQSGRP_OFFCAL_DR2                0x010
#define     DQSGRP_OFFCAL_DR3                0x014
#define     DQSGRP_OFFCAL_SR                 0x018
#define     DQSGRP_OE_MD0                    0x01c
#define         dq7_oe_md_offset                                 28
#define         dq7_oe_md_mask                                   0x70000000
#define         dq6_oe_md_offset                                 24
#define         dq6_oe_md_mask                                   0x07000000
#define         dq5_oe_md_offset                                 20
#define         dq5_oe_md_mask                                   0x00700000
#define         dq4_oe_md_offset                                 16
#define         dq4_oe_md_mask                                   0x00070000
#define         dq3_oe_md_offset                                 12
#define         dq3_oe_md_mask                                   0x00007000
#define         dq2_oe_md_offset                                 8
#define         dq2_oe_md_mask                                   0x00000700
#define         dq1_oe_md_offset                                 4
#define         dq1_oe_md_mask                                   0x00000070
#define         dq0_oe_md_offset                                 0
#define         dq0_oe_md_mask                                   0x00000007
#define     DQSGRP_OE_MD1                    0x020
#define         dq_se_oe_md_offset                               12
#define         dq_se_oe_md_mask                                 0x00007000
#define         gate_oe_md_offset                                8
#define         gate_oe_md_mask                                  0x00000700
#define         dqs_oe_md_offset                                 4
#define         dqs_oe_md_mask                                   0x00000070
#define         dm_oe_md_offset                                  0
#define         dm_oe_md_mask                                    0x00000007
#define     DQSGRP_TE_MD0                    0x024
#define         dq7_te_md_offset                                 28
#define         dq7_te_md_mask                                   0x70000000
#define         dq6_te_md_offset                                 24
#define         dq6_te_md_mask                                   0x07000000
#define         dq5_te_md_offset                                 20
#define         dq5_te_md_mask                                   0x00700000
#define         dq4_te_md_offset                                 16
#define         dq4_te_md_mask                                   0x00070000
#define         dq3_te_md_offset                                 12
#define         dq3_te_md_mask                                   0x00007000
#define         dq2_te_md_offset                                 8
#define         dq2_te_md_mask                                   0x00000700
#define         dq1_te_md_offset                                 4
#define         dq1_te_md_mask                                   0x00000070
#define         dq0_te_md_offset                                 0
#define         dq0_te_md_mask                                   0x00000007
#define     DQSGRP_TE_MD1                    0x028
#define         dq_se_te_md_offset                               12
#define         dq_se_te_md_mask                                 0x00007000
#define         gate_te_md_offset                                8
#define         gate_te_md_mask                                  0x00000700
#define         dqs_te_md_offset                                 4
#define         dqs_te_md_mask                                   0x00000070
#define         dm_te_md_offset                                  0
#define         dm_te_md_mask                                    0x00000007
#define     DQSGRP_PDR_MD0                   0x02c
#define         dq7_pdr_md_offset                                28
#define         dq7_pdr_md_mask                                  0x70000000
#define         dq6_pdr_md_offset                                24
#define         dq6_pdr_md_mask                                  0x07000000
#define         dq5_pdr_md_offset                                20
#define         dq5_pdr_md_mask                                  0x00700000
#define         dq4_pdr_md_offset                                16
#define         dq4_pdr_md_mask                                  0x00070000
#define         dq3_pdr_md_offset                                12
#define         dq3_pdr_md_mask                                  0x00007000
#define         dq2_pdr_md_offset                                8
#define         dq2_pdr_md_mask                                  0x00000700
#define         dq1_pdr_md_offset                                4
#define         dq1_pdr_md_mask                                  0x00000070
#define         dq0_pdr_md_offset                                0
#define         dq0_pdr_md_mask                                  0x00000007
#define     DQSGRP_PDR_MD1                   0x030
#define         dq_se_pdr_md_offset                              12
#define         dq_se_pdr_md_mask                                0x00007000
#define         gate_pdr_md_offset                               8
#define         gate_pdr_md_mask                                 0x00000700
#define         dqs_pdr_md_offset                                4
#define         dqs_pdr_md_mask                                  0x00000070
#define         dm_pdr_md_offset                                 0
#define         dm_pdr_md_mask                                   0x00000007
#define     DQSGRP_QS_GATE_SR                0x038
#define         QS_GATE_SR_STATUS_offset                         1
#define         QS_GATE_SR_STATUS_mask                           0x00000006
#define         QS_GATE_SR_RESP_offset                           0
#define         QS_GATE_SR_RESP_mask                             0x00000001
#define     DQSGRP_GLOBAL_CR                 0x03c
#define         dx_ac_polar_offset                               28
#define         dx_ac_polar_mask                                 0x10000000
#define         dx_ac_mux_offset                                 10
#define         dx_ac_mux_mask                                   0x0ffffc00
#define         rd_fifo_rst_n_dx_ac_sel_offset                   9
#define         rd_fifo_rst_n_dx_ac_sel_mask                     0x00000200
#define         oe_polar_offset                                  8
#define         oe_polar_mask                                    0x00000100
#define         dx_ac_soft_rst_n_offset                          4
#define         dx_ac_soft_rst_n_mask                            0x000000f0
#define         GLB_CR_SDS_RST_EN_offset                         0
#define         GLB_CR_SDS_RST_EN_mask                           0x0000000f
#define     DQSGRP_DLY_BDL                   0x040
#define         rdqs_lcdl_ovrd_offset                            9
#define         rdqs_lcdl_ovrd_mask                              0x00000200
#define         rdqs_lcdl_dly_local_offset                       0
#define         rdqs_lcdl_dly_local_mask                         0x000001ff
#define     DQSGRP_GLB_CR1                   0x044
#define         tx_rst_n_late_offset                             18
#define         tx_rst_n_late_mask                               0x001c0000
#define         tx_rst_n_late_mux_offset                         0
#define         tx_rst_n_late_mux_mask                           0x0003ffff
#define     DQSGRP_DCC_CR                    0x048
#define         cfg_dcc_ovrd_data_offset                         12
#define         cfg_dcc_ovrd_data_mask                           0x0003f000
#define         cfg_dcc_ovrd_en_offset                           11
#define         cfg_dcc_ovrd_en_mask                             0x00000800
#define         cfg_dcc_disable_offset                           10
#define         cfg_dcc_disable_mask                             0x00000400
#define         cfg_dcc_clk_div_num_offset                       0
#define         cfg_dcc_clk_div_num_mask                         0x000003ff
#define     DQSGRP_DCC_SR                    0x04c
#define         dcc_en_offset                                    10
#define         dcc_en_mask                                      0x00000400
#define         dcc_done_offset                                  9
#define         dcc_done_mask                                    0x00000200
#define         pol_offset                                       8
#define         pol_mask                                         0x00000100
#define         dutyx_offset                                     2
#define         dutyx_mask                                       0x000000fc
#define         overflow_offset                                  1
#define         overflow_mask                                    0x00000002
#define         underflow_offset                                 0
#define         underflow_mask                                   0x00000001
#define     DQSGRP_DLY_BYP                   0x050
#define         rx_bdl_byp_offset                                16
#define         rx_bdl_byp_mask                                  0x3fff0000
#define         tx_bdl_byp_offset                                0
#define         tx_bdl_byp_mask                                  0x00003fff
#define     DQSGRP_AA_EN                     0x054
#define         rx_aa_en_offset                                  16
#define         rx_aa_en_mask                                    0x3fff0000
#define         tx_aa_en_offset                                  0
#define         tx_aa_en_mask                                    0x00003fff
#define     DQSGRP_LCDL_OTPC                 0x058
#define         otpc_aa_en_offset                                23
#define         otpc_aa_en_mask                                  0x07800000
#define         lcdl_aa_en_offset                                16
#define         lcdl_aa_en_mask                                  0x007f0000
#define         otpc_dly_byp_offset                              7
#define         otpc_dly_byp_mask                                0x00000780
#define         lcdl_dly_byp_offset                              0
#define         lcdl_dly_byp_mask                                0x0000007f
#define     DQSGRP_GLB_CR2                   0x05c
#define         dx_debug_mux_offset                              18
#define         dx_debug_mux_mask                                0x007c0000
#define         tx_rst_n_dis_offset                              0
#define         tx_rst_n_dis_mask                                0x0003ffff
