/*
 * Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#define     BANK_RIDR                             0x0
#define         BANK_ID_offset                                   0
#define         BANK_ID_mask                                     0xffffffff
#define     RW_TEST                          0x4
#define         RW_TEST_offset                                   0
#define         RW_TEST_mask                                     0xffffffff
#define     BK0_DPLL_CR0                     0x8
#define         BK0_CLK_DIV8_PIPE_offset                         27
#define         BK0_CLK_DIV8_PIPE_mask                           0x78000000
#define         BK0_DPLLLOCK_DEPEND_GPLL_offset                  26
#define         BK0_DPLLLOCK_DEPEND_GPLL_mask                    0x04000000
#define         BK0_GPLL_EN_offset                               24
#define         BK0_GPLL_EN_mask                                 0x03000000
#define         BK0_DPLL_WAIT_L_offset                           8
#define         BK0_DPLL_WAIT_L_mask                             0x00ffff00
#define         BK0_DPLL_WAIT_S_offset                           0
#define         BK0_DPLL_WAIT_S_mask                             0x000000ff
#define     BK0_DPLL_CR1                     0xc
#define         BK0_DSKEWPLL_CTRL_SW_INIT_START_offset           22
#define         BK0_DSKEWPLL_CTRL_SW_INIT_START_mask             0x00400000
#define         BK0_DSKEWPLL_CTRL_SW_BYP_offset                  21
#define         BK0_DSKEWPLL_CTRL_SW_BYP_mask                    0x00200000
#define         BK0_DSKEWPLL_CTRL_LP_EN_offset                   20
#define         BK0_DSKEWPLL_CTRL_LP_EN_mask                     0x00100000
#define         BK0_DSKEWPLL_CTRL_HARD_PD_EN_offset              19
#define         BK0_DSKEWPLL_CTRL_HARD_PD_EN_mask                0x00080000
#define         BK0_DSKEWPLL_CTRL_CLR_offset                     18
#define         BK0_DSKEWPLL_CTRL_CLR_mask                       0x00040000
#define         BK0_DPLL_VCOSEL_offset                           13
#define         BK0_DPLL_VCOSEL_mask                             0x00002000
#define         BK0_DPLL_POSTDIV_offset                          10
#define         BK0_DPLL_POSTDIV_mask                            0x00001c00
#define         BK0_DPLL_FBDIV_offset                            8
#define         BK0_DPLL_FBDIV_mask                              0x00000300
#define         BK0_DPLL_REFDIV_offset                           6
#define         BK0_DPLL_REFDIV_mask                             0x000000c0
#define         BK0_DPLL_TESTEN_offset                           5
#define         BK0_DPLL_TESTEN_mask                             0x00000020
#define         BK0_DPLL_TESTSEL_offset                          4
#define         BK0_DPLL_TESTSEL_mask                            0x00000010
#define         BK0_DPLL_PDCAL_offset                            3
#define         BK0_DPLL_PDCAL_mask                              0x00000008
#define         BK0_DPLL_BYPASS_offset                           1
#define         BK0_DPLL_BYPASS_mask                             0x00000002
#define         BK0_DPLL_PD_offset                               0
#define         BK0_DPLL_PD_mask                                 0x00000001
#define     BK0_DPLL_SR0                     0x10
#define         BK0_DPLL_TESTOUT_offset                          1
#define         BK0_DPLL_TESTOUT_mask                            0x00000002
#define         BK0_DPLL_LOCK_offset                             0
#define         BK0_DPLL_LOCK_mask                               0x00000001
#define     BK0_DPLL_SR1                     0x14
#define         BK0_DPLL_STATE_STATUS_offset                     1
#define         BK0_DPLL_STATE_STATUS_mask                       0xfffffffe
#define         BK0_DPLL_LOCK_DONE_offset                        0
#define         BK0_DPLL_LOCK_DONE_mask                          0x00000001
#define     BK0_DPLL_FRQ_CHK_CTL             0x18
#define         BK0_DPLL_DET_DIS_offset                          0
#define         BK0_DPLL_DET_DIS_mask                            0x00000001
#define     BK0_DPLL_TGT_HTHD                0x1c
#define         BK0_DPLL_TGTCLK_CNT_HTHD_offset                  0
#define         BK0_DPLL_TGTCLK_CNT_HTHD_mask                    0xffffffff
#define     BK0_DPLL_TGT_LTHD                0x20
#define         BK0_DPLL_TGTCLK_CNT_LTHD_offset                  0
#define         BK0_DPLL_TGTCLK_CNT_LTHD_mask                    0xffffffff
#define     BK0_DPLL_REF_THD                 0x24
#define         BK0_DPLL_REFCLK_CNT_THD_offset                   0
#define         BK0_DPLL_REFCLK_CNT_THD_mask                     0x0000ffff
#define     BK0_DPLL_ERR_DET                 0x28
#define         BK0_DPLL_ERR_CLKDET_offset                       0
#define         BK0_DPLL_ERR_CLKDET_mask                         0x00000001
#define     BK0_GLOBAL_CTRL0                 0x2c
#define         BK0_BYTE_DISABLE_offset                          0
#define         BK0_BYTE_DISABLE_mask                            0x0000000f
#define     BK0_DIV_CTRL                     0x30
#define         BK0_DDR_CLK_INV_offset                           25
#define         BK0_DDR_CLK_INV_mask                             0x02000000
#define         BK0_CTL_CLK_INV_offset                           24
#define         BK0_CTL_CLK_INV_mask                             0x01000000
#define         BK0_CTL_CLK_DIV_MASK_offset                      20
#define         BK0_CTL_CLK_DIV_MASK_mask                        0x00f00000
#define         BK0_CTL_CLK_DIV_OUT_offset                       16
#define         BK0_CTL_CLK_DIV_OUT_mask                         0x000f0000
#define         BK0_DDR_CLK_DIV_MASK_offset                      12
#define         BK0_DDR_CLK_DIV_MASK_mask                        0x0000f000
#define         BK0_DDR_CLK_DIV_OUT_offset                       8
#define         BK0_DDR_CLK_DIV_OUT_mask                         0x00000f00
#define         BK0_CLK_DIV_NUM_offset                           4
#define         BK0_CLK_DIV_NUM_mask                             0x000000f0
#define         BK0_CLK_DIV_STEP_offset                          0
#define         BK0_CLK_DIV_STEP_mask                            0x0000000f
#define     BK0_RW_TEST                      0x34
#define         BK0_RW_TEST_offset                               0
#define         BK0_RW_TEST_mask                                 0xffffffff
#define     BK1_DPLL_CR0                     0x38
#define         BK1_CLK_DIV8_PIPE_offset                         27
#define         BK1_CLK_DIV8_PIPE_mask                           0x78000000
#define         BK1_DPLLLOCK_DEPEND_GPLL_offset                  26
#define         BK1_DPLLLOCK_DEPEND_GPLL_mask                    0x04000000
#define         BK1_GPLL_EN_offset                               24
#define         BK1_GPLL_EN_mask                                 0x03000000
#define         BK1_DPLL_WAIT_L_offset                           8
#define         BK1_DPLL_WAIT_L_mask                             0x00ffff00
#define         BK1_DPLL_WAIT_S_offset                           0
#define         BK1_DPLL_WAIT_S_mask                             0x000000ff
#define     BK1_DPLL_CR1                     0x3c
#define         BK1_DSKEWPLL_CTRL_SW_INIT_START_offset           22
#define         BK1_DSKEWPLL_CTRL_SW_INIT_START_mask             0x00400000
#define         BK1_DSKEWPLL_CTRL_SW_BYP_offset                  21
#define         BK1_DSKEWPLL_CTRL_SW_BYP_mask                    0x00200000
#define         BK1_DSKEWPLL_CTRL_LP_EN_offset                   20
#define         BK1_DSKEWPLL_CTRL_LP_EN_mask                     0x00100000
#define         BK1_DSKEWPLL_CTRL_HARD_PD_EN_offset              19
#define         BK1_DSKEWPLL_CTRL_HARD_PD_EN_mask                0x00080000
#define         BK1_DSKEWPLL_CTRL_CLR_offset                     18
#define         BK1_DSKEWPLL_CTRL_CLR_mask                       0x00040000
#define         BK1_DPLL_VCOSEL_offset                           13
#define         BK1_DPLL_VCOSEL_mask                             0x00002000
#define         BK1_DPLL_POSTDIV_offset                          10
#define         BK1_DPLL_POSTDIV_mask                            0x00001c00
#define         BK1_DPLL_FBDIV_offset                            8
#define         BK1_DPLL_FBDIV_mask                              0x00000300
#define         BK1_DPLL_REFDIV_offset                           6
#define         BK1_DPLL_REFDIV_mask                             0x000000c0
#define         BK1_DPLL_TESTEN_offset                           5
#define         BK1_DPLL_TESTEN_mask                             0x00000020
#define         BK1_DPLL_TESTSEL_offset                          4
#define         BK1_DPLL_TESTSEL_mask                            0x00000010
#define         BK1_DPLL_PDCAL_offset                            3
#define         BK1_DPLL_PDCAL_mask                              0x00000008
#define         BK1_DPLL_BYPASS_offset                           1
#define         BK1_DPLL_BYPASS_mask                             0x00000002
#define         BK1_DPLL_PD_offset                               0
#define         BK1_DPLL_PD_mask                                 0x00000001
#define     BK1_DPLL_SR0                     0x40
#define         BK1_DPLL_TESTOUT_offset                          1
#define         BK1_DPLL_TESTOUT_mask                            0x00000002
#define         BK1_DPLL_LOCK_offset                             0
#define         BK1_DPLL_LOCK_mask                               0x00000001
#define     BK1_DPLL_SR1                     0x44
#define         BK1_DPLL_STATE_STATUS_offset                     1
#define         BK1_DPLL_STATE_STATUS_mask                       0xfffffffe
#define         BK1_DPLL_LOCK_DONE_offset                        0
#define         BK1_DPLL_LOCK_DONE_mask                          0x00000001
#define     BK1_DPLL_FRQ_CHK_CTL             0x48
#define         BK1_DPLL_DET_DIS_offset                          0
#define         BK1_DPLL_DET_DIS_mask                            0x00000001
#define     BK1_DPLL_TGT_HTHD                0x4c
#define         BK1_DPLL_TGTCLK_CNT_HTHD_offset                  0
#define         BK1_DPLL_TGTCLK_CNT_HTHD_mask                    0xffffffff
#define     BK1_DPLL_TGT_LTHD                0x50
#define         BK1_DPLL_TGTCLK_CNT_LTHD_offset                  0
#define         BK1_DPLL_TGTCLK_CNT_LTHD_mask                    0xffffffff
#define     BK1_DPLL_REF_THD                 0x54
#define         BK1_DPLL_REFCLK_CNT_THD_offset                   0
#define         BK1_DPLL_REFCLK_CNT_THD_mask                     0x0000ffff
#define     BK1_DPLL_ERR_DET                 0x58
#define         BK1_DPLL_ERR_CLKDET_offset                       0
#define         BK1_DPLL_ERR_CLKDET_mask                         0x00000001
#define     BK1_GLOBAL_CTRL0                 0x5c
#define         BK1_BYTE_DISABLE_offset                          0
#define         BK1_BYTE_DISABLE_mask                            0x0000000f
#define     BK1_DIV_CTRL                     0x60
#define         BK1_DDR_CLK_INV_offset                           25
#define         BK1_DDR_CLK_INV_mask                             0x02000000
#define         BK1_CTL_CLK_INV_offset                           24
#define         BK1_CTL_CLK_INV_mask                             0x01000000
#define         BK1_CTL_CLK_DIV_MASK_offset                      20
#define         BK1_CTL_CLK_DIV_MASK_mask                        0x00f00000
#define         BK1_CTL_CLK_DIV_OUT_offset                       16
#define         BK1_CTL_CLK_DIV_OUT_mask                         0x000f0000
#define         BK1_DDR_CLK_DIV_MASK_offset                      12
#define         BK1_DDR_CLK_DIV_MASK_mask                        0x0000f000
#define         BK1_DDR_CLK_DIV_OUT_offset                       8
#define         BK1_DDR_CLK_DIV_OUT_mask                         0x00000f00
#define         BK1_CLK_DIV_NUM_offset                           4
#define         BK1_CLK_DIV_NUM_mask                             0x000000f0
#define         BK1_CLK_DIV_STEP_offset                          0
#define         BK1_CLK_DIV_STEP_mask                            0x0000000f
#define     BK0_DEBUG_DIV_CTRL               0x64
#define         BK0_DPLL_CTL_CLK_DIV_NUM_offset                  15
#define         BK0_DPLL_CTL_CLK_DIV_NUM_mask                    0x001f8000
#define         BK0_DPLL_CTL_CLK_DIV_BYP_offset                  14
#define         BK0_DPLL_CTL_CLK_DIV_BYP_mask                    0x00004000
#define         BK0_DPLL_8X_CLK_DIV_NUM_offset                   8
#define         BK0_DPLL_8X_CLK_DIV_NUM_mask                     0x00003f00
#define         BK0_DPLL_8X_CLK_DIV_BYP_offset                   7
#define         BK0_DPLL_8X_CLK_DIV_BYP_mask                     0x00000080
#define         BK0_DPLL_TESTOUT_DIV_NUM_offset                  1
#define         BK0_DPLL_TESTOUT_DIV_NUM_mask                    0x0000007e
#define         BK0_DPLL_TESTOUT_DIV_BYP_offset                  0
#define         BK0_DPLL_TESTOUT_DIV_BYP_mask                    0x00000001
#define     BK1_DEBUG_DIV_CTRL               0x68
#define         BK1_DPLL_CTL_CLK_DIV_NUM_offset                  15
#define         BK1_DPLL_CTL_CLK_DIV_NUM_mask                    0x001f8000
#define         BK1_DPLL_CTL_CLK_DIV_BYP_offset                  14
#define         BK1_DPLL_CTL_CLK_DIV_BYP_mask                    0x00004000
#define         BK1_DPLL_8X_CLK_DIV_NUM_offset                   8
#define         BK1_DPLL_8X_CLK_DIV_NUM_mask                     0x00003f00
#define         BK1_DPLL_8X_CLK_DIV_BYP_offset                   7
#define         BK1_DPLL_8X_CLK_DIV_BYP_mask                     0x00000080
#define         BK1_DPLL_TESTOUT_DIV_NUM_offset                  1
#define         BK1_DPLL_TESTOUT_DIV_NUM_mask                    0x0000007e
#define         BK1_DPLL_TESTOUT_DIV_BYP_offset                  0
#define         BK1_DPLL_TESTOUT_DIV_BYP_mask                    0x00000001
#define     BK1_RW_TEST                      0x6c
#define         BK1_RW_TEST_offset                               0
#define         BK1_RW_TEST_mask                                 0xffffffff
