#define     MSTR                             0x000
#define         device_config_offset                             30
#define         device_config_mask                               0xc0000000
#define         burst_rdwr_offset                                16
#define         burst_rdwr_mask                                  0x000f0000
#define         dll_off_mode_offset                              15
#define         dll_off_mode_mask                                0x00008000
#define         data_bus_width_offset                            12
#define         data_bus_width_mask                              0x00003000
#define         geardown_mode_offset                             11
#define         geardown_mode_mask                               0x00000800
#define         en_2t_timing_mode_offset                         10
#define         en_2t_timing_mode_mask                           0x00000400
#define         burstchop_offset                                 9
#define         burstchop_mask                                   0x00000200
#define         ddr4_offset                                      4
#define         ddr4_mask                                        0x00000010
#define         ddr3_offset                                      0
#define         ddr3_mask                                        0x00000001
#define     STAT                             0x004
#define         selfref_cam_not_empty_offset                     12
#define         selfref_cam_not_empty_mask                       0x00001000
#define         selfref_type_offset                              4
#define         selfref_type_mask                                0x00000030
#define         operating_mode_offset                            0
#define         operating_mode_mask                              0x00000007
#define     MRCTRL0                          0x010
#define         mr_wr_offset                                     31
#define         mr_wr_mask                                       0x80000000
#define         pba_mode_offset                                  30
#define         pba_mode_mask                                    0x40000000
#define         mr_addr_offset                                   12
#define         mr_addr_mask                                     0x0000f000
#define         mr_rank_offset                                   4
#define         mr_rank_mask                                     0x00000010
#define         sw_init_int_offset                               3
#define         sw_init_int_mask                                 0x00000008
#define         pda_en_offset                                    2
#define         pda_en_mask                                      0x00000004
#define         mpr_en_offset                                    1
#define         mpr_en_mask                                      0x00000002
#define         mr_type_offset                                   0
#define         mr_type_mask                                     0x00000001
#define     MRCTRL1                          0x014
#define         mr_data_offset                                   0
#define         mr_data_mask                                     0x0003ffff
#define     MRSTAT                           0x018
#define         pda_done_offset                                  8
#define         pda_done_mask                                    0x00000100
#define         mr_wr_busy_offset                                0
#define         mr_wr_busy_mask                                  0x00000001
#define     MRCTRL2                          0x01c
#define         mr_device_sel_offset                             0
#define         mr_device_sel_mask                               0xffffffff
#define     PWRCTL                           0x030
#define         dis_cam_drain_selfref_offset                     7
#define         dis_cam_drain_selfref_mask                       0x00000080
#define         selfref_sw_offset                                5
#define         selfref_sw_mask                                  0x00000020
#define         mpsm_en_offset                                   4
#define         mpsm_en_mask                                     0x00000010
#define         en_dfi_dram_clk_disable_offset                   3
#define         en_dfi_dram_clk_disable_mask                     0x00000008
#define         powerdown_en_offset                              1
#define         powerdown_en_mask                                0x00000002
#define         selfref_en_offset                                0
#define         selfref_en_mask                                  0x00000001
#define     PWRTMG                           0x034
#define         selfref_to_x32_offset                            16
#define         selfref_to_x32_mask                              0x00ff0000
#define         powerdown_to_x32_offset                          0
#define         powerdown_to_x32_mask                            0x0000001f
#define     HWLPCTL                          0x038
#define         hw_lp_idle_x32_offset                            16
#define         hw_lp_idle_x32_mask                              0x0fff0000
#define         hw_lp_exit_idle_en_offset                        1
#define         hw_lp_exit_idle_en_mask                          0x00000002
#define         hw_lp_en_offset                                  0
#define         hw_lp_en_mask                                    0x00000001
#define     RFSHCTL0                         0x050
#define         refresh_margin_offset                            20
#define         refresh_margin_mask                              0x00f00000
#define         refresh_to_x1_x32_offset                         12
#define         refresh_to_x1_x32_mask                           0x0001f000
#define         refresh_burst_offset                             4
#define         refresh_burst_mask                               0x000003f0
#define     RFSHCTL3                         0x060
#define         refresh_mode_offset                              4
#define         refresh_mode_mask                                0x00000070
#define         refresh_update_level_offset                      1
#define         refresh_update_level_mask                        0x00000002
#define         dis_auto_refresh_offset                          0
#define         dis_auto_refresh_mask                            0x00000001
#define     RFSHTMG                          0x064
#define         t_rfc_nom_x1_x32_offset                          16
#define         t_rfc_nom_x1_x32_mask                            0x0fff0000
#define         t_rfc_min_offset                                 0
#define         t_rfc_min_mask                                   0x000003ff
#define     ECCCFG0                          0x070
#define         dis_scrub_offset                                 4
#define         dis_scrub_mask                                   0x00000010
#define         ecc_mode_offset                                  0
#define         ecc_mode_mask                                    0x00000007
#define     ECCCFG1                          0x074
#define         data_poison_bit_offset                           1
#define         data_poison_bit_mask                             0x00000002
#define         data_poison_en_offset                            0
#define         data_poison_en_mask                              0x00000001
#define     ECCSTAT                          0x078
#define         ecc_uncorrected_err_offset                       16
#define         ecc_uncorrected_err_mask                         0x000f0000
#define         ecc_corrected_err_offset                         8
#define         ecc_corrected_err_mask                           0x00000f00
#define         ecc_corrected_bit_num_offset                     0
#define         ecc_corrected_bit_num_mask                       0x0000007f
#define     ECCCTL                           0x07c
#define         ecc_uncorrected_err_intr_force_offset            17
#define         ecc_uncorrected_err_intr_force_mask              0x00020000
#define         ecc_corrected_err_intr_force_offset              16
#define         ecc_corrected_err_intr_force_mask                0x00010000
#define         ecc_uncorrected_err_intr_en_offset               9
#define         ecc_uncorrected_err_intr_en_mask                 0x00000200
#define         ecc_corrected_err_intr_en_offset                 8
#define         ecc_corrected_err_intr_en_mask                   0x00000100
#define         ecc_uncorr_err_cnt_clr_offset                    3
#define         ecc_uncorr_err_cnt_clr_mask                      0x00000008
#define         ecc_corr_err_cnt_clr_offset                      2
#define         ecc_corr_err_cnt_clr_mask                        0x00000004
#define         ecc_uncorrected_err_clr_offset                   1
#define         ecc_uncorrected_err_clr_mask                     0x00000002
#define         ecc_corrected_err_clr_offset                     0
#define         ecc_corrected_err_clr_mask                       0x00000001
#define     ECCERRCNT                        0x080
#define         ecc_uncorr_err_cnt_offset                        16
#define         ecc_uncorr_err_cnt_mask                          0xffff0000
#define         ecc_corr_err_cnt_offset                          0
#define         ecc_corr_err_cnt_mask                            0x0000ffff
#define     ECCCADDR0                        0x084
#define         ecc_corr_row_offset                              0
#define         ecc_corr_row_mask                                0x0003ffff
#define     ECCCADDR1                        0x088
#define         ecc_corr_bg_offset                               24
#define         ecc_corr_bg_mask                                 0x03000000
#define         ecc_corr_bank_offset                             16
#define         ecc_corr_bank_mask                               0x00070000
#define         ecc_corr_col_offset                              0
#define         ecc_corr_col_mask                                0x00000fff
#define     ECCCSYN0                         0x08c
#define         ecc_corr_syndromes_31_0_offset                   0
#define         ecc_corr_syndromes_31_0_mask                     0xffffffff
#define     ECCCSYN2                         0x094
#define         ecc_corr_syndromes_71_64_offset                  0
#define         ecc_corr_syndromes_71_64_mask                    0x000000ff
#define     ECCBITMASK0                      0x098
#define         ecc_corr_bit_mask_31_0_offset                    0
#define         ecc_corr_bit_mask_31_0_mask                      0xffffffff
#define     ECCBITMASK2                      0x0a0
#define         ecc_corr_bit_mask_71_64_offset                   0
#define         ecc_corr_bit_mask_71_64_mask                     0x000000ff
#define     ECCUADDR0                        0x0a4
#define         ecc_uncorr_row_offset                            0
#define         ecc_uncorr_row_mask                              0x0003ffff
#define     ECCUADDR1                        0x0a8
#define         ecc_uncorr_bg_offset                             24
#define         ecc_uncorr_bg_mask                               0x03000000
#define         ecc_uncorr_bank_offset                           16
#define         ecc_uncorr_bank_mask                             0x00070000
#define         ecc_uncorr_col_offset                            0
#define         ecc_uncorr_col_mask                              0x00000fff
#define     ECCUSYN0                         0x0ac
#define         ecc_uncorr_syndromes_31_0_offset                 0
#define         ecc_uncorr_syndromes_31_0_mask                   0xffffffff
#define     ECCUSYN2                         0x0b4
#define         ecc_uncorr_syndromes_71_64_offset                0
#define         ecc_uncorr_syndromes_71_64_mask                  0x000000ff
#define     ECCPOISONADDR0                   0x0b8
#define         ecc_poison_col_offset                            0
#define         ecc_poison_col_mask                              0x00000fff
#define     ECCPOISONADDR1                   0x0bc
#define         ecc_poison_bg_offset                             28
#define         ecc_poison_bg_mask                               0x30000000
#define         ecc_poison_bank_offset                           24
#define         ecc_poison_bank_mask                             0x07000000
#define         ecc_poison_row_offset                            0
#define         ecc_poison_row_mask                              0x0003ffff
#define     CRCPARCTL0                       0x0c0
#define         dfi_alert_err_cnt_clr_offset                     2
#define         dfi_alert_err_cnt_clr_mask                       0x00000004
#define         dfi_alert_err_int_clr_offset                     1
#define         dfi_alert_err_int_clr_mask                       0x00000002
#define         dfi_alert_err_int_en_offset                      0
#define         dfi_alert_err_int_en_mask                        0x00000001
#define     CRCPARCTL1                       0x0c4
#define         caparity_disable_before_sr_offset                12
#define         caparity_disable_before_sr_mask                  0x00001000
#define         crc_inc_dm_offset                                7
#define         crc_inc_dm_mask                                  0x00000080
#define         crc_enable_offset                                4
#define         crc_enable_mask                                  0x00000010
#define         parity_enable_offset                             0
#define         parity_enable_mask                               0x00000001
#define     CRCPARSTAT                       0x0cc
#define         dfi_alert_err_int_offset                         16
#define         dfi_alert_err_int_mask                           0x00010000
#define         dfi_alert_err_cnt_offset                         0
#define         dfi_alert_err_cnt_mask                           0x0000ffff
#define     INIT0                            0x0d0
#define         skip_dram_init_offset                            30
#define         skip_dram_init_mask                              0xc0000000
#define         post_cke_x1024_offset                            16
#define         post_cke_x1024_mask                              0x03ff0000
#define         pre_cke_x1024_offset                             0
#define         pre_cke_x1024_mask                               0x00000fff
#define     INIT1                            0x0d4
#define         dram_rstn_x1024_offset                           16
#define         dram_rstn_x1024_mask                             0x01ff0000
#define         pre_ocd_x32_offset                               0
#define         pre_ocd_x32_mask                                 0x0000000f
#define     INIT3                            0x0dc
#define         mr_offset                                        16
#define         mr_mask                                          0xffff0000
#define         emr_offset                                       0
#define         emr_mask                                         0x0000ffff
#define     INIT4                            0x0e0
#define         emr2_offset                                      16
#define         emr2_mask                                        0xffff0000
#define         emr3_offset                                      0
#define         emr3_mask                                        0x0000ffff
#define     INIT5                            0x0e4
#define         dev_zqinit_x32_offset                            16
#define         dev_zqinit_x32_mask                              0x00ff0000
#define     INIT6                            0x0e8
#define         mr4_offset                                       16
#define         mr4_mask                                         0xffff0000
#define         mr5_offset                                       0
#define         mr5_mask                                         0x0000ffff
#define     INIT7                            0x0ec
#define         mr6_offset                                       0
#define         mr6_mask                                         0x0000ffff
#define     DIMMCTL                          0x0f0
#define         rcd_b_output_disabled_offset                     14
#define         rcd_b_output_disabled_mask                       0x00004000
#define         rcd_a_output_disabled_offset                     13
#define         rcd_a_output_disabled_mask                       0x00002000
#define         rcd_weak_drive_offset                            12
#define         rcd_weak_drive_mask                              0x00001000
#define         lrdimm_bcom_cmd_prot_offset                      6
#define         lrdimm_bcom_cmd_prot_mask                        0x00000040
#define         dimm_dis_bg_mirroring_offset                     5
#define         dimm_dis_bg_mirroring_mask                       0x00000020
#define         mrs_bg1_en_offset                                4
#define         mrs_bg1_en_mask                                  0x00000010
#define         mrs_a17_en_offset                                3
#define         mrs_a17_en_mask                                  0x00000008
#define         dimm_output_inv_en_offset                        2
#define         dimm_output_inv_en_mask                          0x00000004
#define         dimm_addr_mirr_en_offset                         1
#define         dimm_addr_mirr_en_mask                           0x00000002
#define         dimm_stagger_cs_en_offset                        0
#define         dimm_stagger_cs_en_mask                          0x00000001
#define     DRAMTMG0                         0x100
#define         wr2pre_offset                                    24
#define         wr2pre_mask                                      0x7f000000
#define         t_faw_offset                                     16
#define         t_faw_mask                                       0x003f0000
#define         t_ras_max_offset                                 8
#define         t_ras_max_mask                                   0x00007f00
#define         t_ras_min_offset                                 0
#define         t_ras_min_mask                                   0x0000003f
#define     DRAMTMG1                         0x104
#define         t_xp_offset                                      16
#define         t_xp_mask                                        0x001f0000
#define         rd2pre_offset                                    8
#define         rd2pre_mask                                      0x00003f00
#define         t_rc_offset                                      0
#define         t_rc_mask                                        0x0000007f
#define     DRAMTMG2                         0x108
#define         write_latency_offset                             24
#define         write_latency_mask                               0x3f000000
#define         read_latency_offset                              16
#define         read_latency_mask                                0x003f0000
#define         rd2wr_offset                                     8
#define         rd2wr_mask                                       0x00003f00
#define         wr2rd_offset                                     0
#define         wr2rd_mask                                       0x0000003f
#define     DRAMTMG3                         0x10c
#define         t_mrd_offset                                     12
#define         t_mrd_mask                                       0x0003f000
#define         t_mod_offset                                     0
#define         t_mod_mask                                       0x000003ff
#define     DRAMTMG4                         0x110
#define         t_rcd_offset                                     24
#define         t_rcd_mask                                       0x1f000000
#define         t_ccd_offset                                     16
#define         t_ccd_mask                                       0x000f0000
#define         t_rrd_offset                                     8
#define         t_rrd_mask                                       0x00000f00
#define         t_rp_offset                                      0
#define         t_rp_mask                                        0x0000001f
#define     DRAMTMG5                         0x114
#define         t_cksrx_offset                                   24
#define         t_cksrx_mask                                     0x0f000000
#define         t_cksre_offset                                   16
#define         t_cksre_mask                                     0x00ff0000
#define         t_ckesr_offset                                   8
#define         t_ckesr_mask                                     0x0000ff00
#define         t_cke_offset                                     0
#define         t_cke_mask                                       0x0000001f
#define     DRAMTMG8                         0x120
#define         t_xs_fast_x32_offset                             24
#define         t_xs_fast_x32_mask                               0x7f000000
#define         t_xs_abort_x32_offset                            16
#define         t_xs_abort_x32_mask                              0x007f0000
#define         t_xs_dll_x32_offset                              8
#define         t_xs_dll_x32_mask                                0x00007f00
#define         t_xs_x32_offset                                  0
#define         t_xs_x32_mask                                    0x0000007f
#define     DRAMTMG9                         0x124
#define         ddr4_wr_preamble_offset                          30
#define         ddr4_wr_preamble_mask                            0x40000000
#define         t_ccd_s_offset                                   16
#define         t_ccd_s_mask                                     0x00070000
#define         t_rrd_s_offset                                   8
#define         t_rrd_s_mask                                     0x00000f00
#define         wr2rd_s_offset                                   0
#define         wr2rd_s_mask                                     0x0000003f
#define     DRAMTMG10                        0x128
#define         t_sync_gear_offset                               16
#define         t_sync_gear_mask                                 0x001f0000
#define         t_cmd_gear_offset                                8
#define         t_cmd_gear_mask                                  0x00001f00
#define         t_gear_setup_offset                              2
#define         t_gear_setup_mask                                0x0000000c
#define         t_gear_hold_offset                               0
#define         t_gear_hold_mask                                 0x00000003
#define     DRAMTMG11                        0x12c
#define         post_mpsm_gap_x32_offset                         24
#define         post_mpsm_gap_x32_mask                           0x7f000000
#define         t_mpx_lh_offset                                  16
#define         t_mpx_lh_mask                                    0x001f0000
#define         t_mpx_s_offset                                   8
#define         t_mpx_s_mask                                     0x00000300
#define         t_ckmpe_offset                                   0
#define         t_ckmpe_mask                                     0x0000001f
#define     DRAMTMG12                        0x130
#define         t_wr_mpr_offset                                  24
#define         t_wr_mpr_mask                                    0x3f000000
#define         t_mrd_pda_offset                                 0
#define         t_mrd_pda_mask                                   0x0000001f
#define     DRAMTMG15                        0x13c
#define         en_dfi_lp_t_stab_offset                          31
#define         en_dfi_lp_t_stab_mask                            0x80000000
#define         t_stab_x32_offset                                0
#define         t_stab_x32_mask                                  0x000000ff
#define     ZQCTL0                           0x180
#define         dis_auto_zq_offset                               31
#define         dis_auto_zq_mask                                 0x80000000
#define         dis_srx_zqcl_offset                              30
#define         dis_srx_zqcl_mask                                0x40000000
#define         zq_resistor_shared_offset                        29
#define         zq_resistor_shared_mask                          0x20000000
#define         dis_mpsmx_zqcl_offset                            28
#define         dis_mpsmx_zqcl_mask                              0x10000000
#define         t_zq_long_nop_offset                             16
#define         t_zq_long_nop_mask                               0x07ff0000
#define         t_zq_short_nop_offset                            0
#define         t_zq_short_nop_mask                              0x000003ff
#define     ZQCTL1                           0x184
#define         t_zq_short_interval_x1024_offset                 0
#define         t_zq_short_interval_x1024_mask                   0x000fffff
#define     DFITMG0                          0x190
#define         dfi_t_ctrl_delay_offset                          24
#define         dfi_t_ctrl_delay_mask                            0x1f000000
#define         dfi_rddata_use_dfi_phy_clk_offset                23
#define         dfi_rddata_use_dfi_phy_clk_mask                  0x00800000
#define         dfi_t_rddata_en_offset                           16
#define         dfi_t_rddata_en_mask                             0x007f0000
#define         dfi_wrdata_use_dfi_phy_clk_offset                15
#define         dfi_wrdata_use_dfi_phy_clk_mask                  0x00008000
#define         dfi_tphy_wrdata_offset                           8
#define         dfi_tphy_wrdata_mask                             0x00003f00
#define         dfi_tphy_wrlat_offset                            0
#define         dfi_tphy_wrlat_mask                              0x0000003f
#define     DFITMG1                          0x194
#define         dfi_t_cmd_lat_offset                             28
#define         dfi_t_cmd_lat_mask                               0xf0000000
#define         dfi_t_parin_lat_offset                           24
#define         dfi_t_parin_lat_mask                             0x03000000
#define         dfi_t_wrdata_delay_offset                        16
#define         dfi_t_wrdata_delay_mask                          0x001f0000
#define         dfi_t_dram_clk_disable_offset                    8
#define         dfi_t_dram_clk_disable_mask                      0x00001f00
#define         dfi_t_dram_clk_enable_offset                     0
#define         dfi_t_dram_clk_enable_mask                       0x0000001f
#define     DFILPCFG0                        0x198
#define         dfi_tlp_resp_offset                              24
#define         dfi_tlp_resp_mask                                0x1f000000
#define         dfi_lp_wakeup_sr_offset                          12
#define         dfi_lp_wakeup_sr_mask                            0x0000f000
#define         dfi_lp_en_sr_offset                              8
#define         dfi_lp_en_sr_mask                                0x00000100
#define         dfi_lp_wakeup_pd_offset                          4
#define         dfi_lp_wakeup_pd_mask                            0x000000f0
#define         dfi_lp_en_pd_offset                              0
#define         dfi_lp_en_pd_mask                                0x00000001
#define     DFILPCFG1                        0x19c
#define         dfi_lp_wakeup_mpsm_offset                        4
#define         dfi_lp_wakeup_mpsm_mask                          0x000000f0
#define         dfi_lp_en_mpsm_offset                            0
#define         dfi_lp_en_mpsm_mask                              0x00000001
#define     DFIUPD0                          0x1a0
#define         dis_auto_ctrlupd_offset                          31
#define         dis_auto_ctrlupd_mask                            0x80000000
#define         dis_auto_ctrlupd_srx_offset                      30
#define         dis_auto_ctrlupd_srx_mask                        0x40000000
#define         ctrlupd_pre_srx_offset                           29
#define         ctrlupd_pre_srx_mask                             0x20000000
#define         dfi_t_ctrlup_max_offset                          16
#define         dfi_t_ctrlup_max_mask                            0x03ff0000
#define         dfi_t_ctrlup_min_offset                          0
#define         dfi_t_ctrlup_min_mask                            0x000003ff
#define     DFIUPD1                          0x1a4
#define         dfi_t_ctrlupd_interval_min_x1024_offset          16
#define         dfi_t_ctrlupd_interval_min_x1024_mask            0x00ff0000
#define         dfi_t_ctrlupd_interval_max_x1024_offset          0
#define         dfi_t_ctrlupd_interval_max_x1024_mask            0x000000ff
#define     DFIUPD2                          0x1a8
#define         dfi_phyupd_en_offset                             31
#define         dfi_phyupd_en_mask                               0x80000000
#define     DFIMISC                          0x1b0
#define         dfi_frequency_offset                             8
#define         dfi_frequency_mask                               0x00001f00
#define         dis_dyn_adr_tri_offset                           6
#define         dis_dyn_adr_tri_mask                             0x00000040
#define         dfi_init_start_offset                            5
#define         dfi_init_start_mask                              0x00000020
#define         ctl_idle_en_offset                               4
#define         ctl_idle_en_mask                                 0x00000010
// #define         _offset                                          2
// #define         _mask                                            0x00000004
#define         phy_dbi_mode_offset                              1
#define         phy_dbi_mode_mask                                0x00000002
#define         dfi_init_complete_en_offset                      0
#define         dfi_init_complete_en_mask                        0x00000001
#define     DFITMG2                          0x1b4
#define         dfi_tphy_rdcslat_offset                          8
#define         dfi_tphy_rdcslat_mask                            0x00007f00
#define         dfi_tphy_wrcslat_offset                          0
#define         dfi_tphy_wrcslat_mask                            0x0000003f
#define     DFITMG3                          0x1b8
#define         dfi_t_geardown_delay_offset                      0
#define         dfi_t_geardown_delay_mask                        0x0000001f
#define     DFISTAT                          0x1bc
#define         dfi_lp_ack_offset                                1
#define         dfi_lp_ack_mask                                  0x00000002
#define         dfi_init_complete_offset                         0
#define         dfi_init_complete_mask                           0x00000001
#define     DBICTL                           0x1c0
#define         rd_dbi_en_offset                                 2
#define         rd_dbi_en_mask                                   0x00000004
#define         wr_dbi_en_offset                                 1
#define         wr_dbi_en_mask                                   0x00000002
#define         dm_en_offset                                     0
#define         dm_en_mask                                       0x00000001
#define     DFIPHYMSTR                       0x1c4
#define         dfi_phymstr_blk_ref_x32_offset                   24
#define         dfi_phymstr_blk_ref_x32_mask                     0xff000000
#define         dfi_phymstr_en_offset                            0
#define         dfi_phymstr_en_mask                              0x00000001
#define     ADDRMAP1                         0x204
#define         addrmap_bank_b2_offset                           16
#define         addrmap_bank_b2_mask                             0x003f0000
#define         addrmap_bank_b1_offset                           8
#define         addrmap_bank_b1_mask                             0x00003f00
#define         addrmap_bank_b0_offset                           0
#define         addrmap_bank_b0_mask                             0x0000003f
#define     ADDRMAP2                         0x208
#define         addrmap_col_b5_offset                            24
#define         addrmap_col_b5_mask                              0x0f000000
#define         addrmap_col_b4_offset                            16
#define         addrmap_col_b4_mask                              0x000f0000
#define         addrmap_col_b3_offset                            8
#define         addrmap_col_b3_mask                              0x00001f00
#define         addrmap_col_b2_offset                            0
#define         addrmap_col_b2_mask                              0x0000000f
#define     ADDRMAP3                         0x20c
#define         addrmap_col_b9_offset                            24
#define         addrmap_col_b9_mask                              0x1f000000
#define         addrmap_col_b8_offset                            16
#define         addrmap_col_b8_mask                              0x001f0000
#define         addrmap_col_b7_offset                            8
#define         addrmap_col_b7_mask                              0x00001f00
#define         addrmap_col_b6_offset                            0
#define         addrmap_col_b6_mask                              0x0000001f
#define     ADDRMAP4                         0x210
#define         addrmap_col_b11_offset                           8
#define         addrmap_col_b11_mask                             0x00001f00
#define         addrmap_col_b10_offset                           0
#define         addrmap_col_b10_mask                             0x0000001f
#define     ADDRMAP5                         0x214
#define         addrmap_row_b11_offset                           24
#define         addrmap_row_b11_mask                             0x0f000000
#define         addrmap_row_b2_10_offset                         16
#define         addrmap_row_b2_10_mask                           0x000f0000
#define         addrmap_row_b1_offset                            8
#define         addrmap_row_b1_mask                              0x00000f00
#define         addrmap_row_b0_offset                            0
#define         addrmap_row_b0_mask                              0x0000000f
#define     ADDRMAP6                         0x218
#define         addrmap_row_b15_offset                           24
#define         addrmap_row_b15_mask                             0x0f000000
#define         addrmap_row_b14_offset                           16
#define         addrmap_row_b14_mask                             0x000f0000
#define         addrmap_row_b13_offset                           8
#define         addrmap_row_b13_mask                             0x00000f00
#define         addrmap_row_b12_offset                           0
#define         addrmap_row_b12_mask                             0x0000000f
#define     ADDRMAP7                         0x21c
#define         addrmap_row_b17_offset                           8
#define         addrmap_row_b17_mask                             0x00000f00
#define         addrmap_row_b16_offset                           0
#define         addrmap_row_b16_mask                             0x0000000f
#define     ADDRMAP8                         0x220
#define         addrmap_bg_b1_offset                             8
#define         addrmap_bg_b1_mask                               0x00003f00
#define         addrmap_bg_b0_offset                             0
#define         addrmap_bg_b0_mask                               0x0000003f
#define     ADDRMAP9                         0x224
#define         addrmap_row_b5_offset                            24
#define         addrmap_row_b5_mask                              0x0f000000
#define         addrmap_row_b4_offset                            16
#define         addrmap_row_b4_mask                              0x000f0000
#define         addrmap_row_b3_offset                            8
#define         addrmap_row_b3_mask                              0x00000f00
#define         addrmap_row_b2_offset                            0
#define         addrmap_row_b2_mask                              0x0000000f
#define     ADDRMAP10                        0x228
#define         addrmap_row_b9_offset                            24
#define         addrmap_row_b9_mask                              0x0f000000
#define         addrmap_row_b8_offset                            16
#define         addrmap_row_b8_mask                              0x000f0000
#define         addrmap_row_b7_offset                            8
#define         addrmap_row_b7_mask                              0x00000f00
#define         addrmap_row_b6_offset                            0
#define         addrmap_row_b6_mask                              0x0000000f
#define     ADDRMAP11                        0x22c
#define         addrmap_row_b10_offset                           0
#define         addrmap_row_b10_mask                             0x0000000f
#define     ODTCFG                           0x240
#define         wr_odt_hold_offset                               24
#define         wr_odt_hold_mask                                 0x0f000000
#define         wr_odt_delay_offset                              16
#define         wr_odt_delay_mask                                0x001f0000
#define         rd_odt_hold_offset                               8
#define         rd_odt_hold_mask                                 0x00000f00
#define         rd_odt_delay_offset                              2
#define         rd_odt_delay_mask                                0x0000007c
#define     ODTMAP                           0x244
#define         rank0_rd_odt_offset                              4
#define         rank0_rd_odt_mask                                0x00000010
#define         rank0_wr_odt_offset                              0
#define         rank0_wr_odt_mask                                0x00000001
#define     SCHED                            0x250
#define         rdwr_idle_gap_offset                             24
#define         rdwr_idle_gap_mask                               0x7f000000
#define         go2critical_hysteresis_offset                    16
#define         go2critical_hysteresis_mask                      0x00ff0000
#define         lpr_num_entries_offset                           8
#define         lpr_num_entries_mask                             0x00001f00
#define         autopre_rmw_offset                               7
#define         autopre_rmw_mask                                 0x00000080
#define         pageclose_offset                                 2
#define         pageclose_mask                                   0x00000004
#define         prefer_write_offset                              1
#define         prefer_write_mask                                0x00000002
#define     SCHED1                           0x254
#define         pageclose_timer_offset                           0
#define         pageclose_timer_mask                             0x000000ff
#define     PERFHPR1                         0x25c
#define         hpr_xact_run_length_offset                       24
#define         hpr_xact_run_length_mask                         0xff000000
#define         hpr_max_starve_offset                            0
#define         hpr_max_starve_mask                              0x0000ffff
#define     PERFLPR1                         0x264
#define         lpr_xact_run_length_offset                       24
#define         lpr_xact_run_length_mask                         0xff000000
#define         lpr_max_starve_offset                            0
#define         lpr_max_starve_mask                              0x0000ffff
#define     PERFWR1                          0x26c
#define         w_xact_run_length_offset                         24
#define         w_xact_run_length_mask                           0xff000000
#define         w_max_starve_offset                              0
#define         w_max_starve_mask                                0x0000ffff
#define     DBG0                             0x300
#define         dis_collision_page_opt_offset                    4
#define         dis_collision_page_opt_mask                      0x00000010
#define         dis_wc_offset                                    0
#define         dis_wc_mask                                      0x00000001
#define     DBG1                             0x304
#define         dis_hif_offset                                   1
#define         dis_hif_mask                                     0x00000002
#define         dis_dq_offset                                    0
#define         dis_dq_mask                                      0x00000001
#define     DBGCAM                           0x308
#define         dbg_stall_rd_offset                              31
#define         dbg_stall_rd_mask                                0x80000000
#define         dbg_stall_wr_offset                              30
#define         dbg_stall_wr_mask                                0x40000000
#define         wr_data_pipeline_empty_offset                    29
#define         wr_data_pipeline_empty_mask                      0x20000000
#define         rd_data_pipeline_empty_offset                    28
#define         rd_data_pipeline_empty_mask                      0x10000000
#define         dbg_wr_q_empty_offset                            26
#define         dbg_wr_q_empty_mask                              0x04000000
#define         dbg_rd_q_empty_offset                            25
#define         dbg_rd_q_empty_mask                              0x02000000
#define         dbg_w_q_depth_offset                             16
#define         dbg_w_q_depth_mask                               0x003f0000
#define         dbg_lpr_q_depth_offset                           8
#define         dbg_lpr_q_depth_mask                             0x00003f00
#define         dbg_hpr_q_depth_offset                           0
#define         dbg_hpr_q_depth_mask                             0x0000003f
#define     DBGCMD                           0x30c
#define         ctrlupd_offset                                   5
#define         ctrlupd_mask                                     0x00000020
#define         zq_calib_short_offset                            4
#define         zq_calib_short_mask                              0x00000010
#define         rank0_refresh_offset                             0
#define         rank0_refresh_mask                               0x00000001
#define     DBGSTAT                          0x310
#define         ctrlupd_busy_offset                              5
#define         ctrlupd_busy_mask                                0x00000020
#define         zq_calib_short_busy_offset                       4
#define         zq_calib_short_busy_mask                         0x00000010
#define         rank0_refresh_busy_offset                        0
#define         rank0_refresh_busy_mask                          0x00000001
#define     SWCTL                            0x320
#define         sw_done_offset                                   0
#define         sw_done_mask                                     0x00000001
#define     SWSTAT                           0x324
#define         sw_done_ack_offset                               0
#define         sw_done_ack_mask                                 0x00000001
#define     SWCTLSTATIC                      0x328
#define         sw_static_unlock_offset                          0
#define         sw_static_unlock_mask                            0x00000001
#define     POISONCFG                        0x36c
#define         rd_poison_intr_clr_offset                        24
#define         rd_poison_intr_clr_mask                          0x01000000
#define         rd_poison_intr_en_offset                         20
#define         rd_poison_intr_en_mask                           0x00100000
#define         rd_poison_slverr_en_offset                       16
#define         rd_poison_slverr_en_mask                         0x00010000
#define         wr_poison_intr_clr_offset                        8
#define         wr_poison_intr_clr_mask                          0x00000100
#define         wr_poison_intr_en_offset                         4
#define         wr_poison_intr_en_mask                           0x00000010
#define         wr_poison_slverr_en_offset                       0
#define         wr_poison_slverr_en_mask                         0x00000001
#define     POISONSTAT                       0x370
#define         rd_poison_intr_3_offset                          19
#define         rd_poison_intr_3_mask                            0x00080000
#define         rd_poison_intr_2_offset                          18
#define         rd_poison_intr_2_mask                            0x00040000
#define         rd_poison_intr_1_offset                          17
#define         rd_poison_intr_1_mask                            0x00020000
#define         rd_poison_intr_0_offset                          16
#define         rd_poison_intr_0_mask                            0x00010000
#define         wr_poison_intr_3_offset                          3
#define         wr_poison_intr_3_mask                            0x00000008
#define         wr_poison_intr_2_offset                          2
#define         wr_poison_intr_2_mask                            0x00000004
#define         wr_poison_intr_1_offset                          1
#define         wr_poison_intr_1_mask                            0x00000002
#define         wr_poison_intr_0_offset                          0
#define         wr_poison_intr_0_mask                            0x00000001
#define     ADVECCINDEX                      0x374
#define         ecc_poison_beats_sel_offset                      5
#define         ecc_poison_beats_sel_mask                        0x000001e0
#define         ecc_err_symbol_sel_offset                        3
#define         ecc_err_symbol_sel_mask                          0x00000018
#define         ecc_syndrome_sel_offset                          0
#define         ecc_syndrome_sel_mask                            0x00000007
#define     ECCPOISONPAT0                    0x37c
#define         ecc_poison_data_31_0_offset                      0
#define         ecc_poison_data_31_0_mask                        0xffffffff
#define     ECCPOISONPAT2                    0x384
#define         ecc_poison_data_71_64_offset                     0
#define         ecc_poison_data_71_64_mask                       0x000000ff
#define     PSTAT                            0x3fc
#define         wr_port_busy_3_offset                            19
#define         wr_port_busy_3_mask                              0x00080000
#define         wr_port_busy_2_offset                            18
#define         wr_port_busy_2_mask                              0x00040000
#define         wr_port_busy_1_offset                            17
#define         wr_port_busy_1_mask                              0x00020000
#define         wr_port_busy_0_offset                            16
#define         wr_port_busy_0_mask                              0x00010000
#define         rd_port_busy_3_offset                            3
#define         rd_port_busy_3_mask                              0x00000008
#define         rd_port_busy_2_offset                            2
#define         rd_port_busy_2_mask                              0x00000004
#define         rd_port_busy_1_offset                            1
#define         rd_port_busy_1_mask                              0x00000002
#define         rd_port_busy_0_offset                            0
#define         rd_port_busy_0_mask                              0x00000001
#define     PCCFG                            0x400
#define         rd_port_pagematch_en_offset                      14
#define         rd_port_pagematch_en_mask                        0x00004000
#define         rd_port_urgent_en_offset                         13
#define         rd_port_urgent_en_mask                           0x00002000
#define         rd_port_aging_en_offset                          12
#define         rd_port_aging_en_mask                            0x00001000
#define         rd_port_priority_offset                          0
#define         rd_port_priority_mask                            0x000003ff
#define     PCFGW_0                          0x408
#define         wr_port_pagematch_en_offset                      14
#define         wr_port_pagematch_en_mask                        0x00004000
#define         wr_port_urgent_en_offset                         13
#define         wr_port_urgent_en_mask                           0x00002000
#define         wr_port_aging_en_offset                          12
#define         wr_port_aging_en_mask                            0x00001000
#define         wr_port_priority_offset                          0
#define         wr_port_priority_mask                            0x000003ff
#define     PCTRL_0                          0x490
#define         port_en_offset                                   0
#define         port_en_mask                                     0x00000001
#define     PCFGQOS0_0                       0x494
#define         rqos_map_region1_offset                          20
#define         rqos_map_region1_mask                            0x00300000
#define         rqos_map_region0_offset                          16
#define         rqos_map_region0_mask                            0x00030000
#define         rqos_map_level1_offset                           0
#define         rqos_map_level1_mask                             0x0000000f
#define     PCFGQOS1_0                       0x498
#define         rqos_map_timeoutr_offset                         16
#define         rqos_map_timeoutr_mask                           0x07ff0000
#define         rqos_map_timeoutb_offset                         0
#define         rqos_map_timeoutb_mask                           0x000007ff
#define     PCFGWQOS0_0                      0x49c
#define         wqos_map_region2_offset                          24
#define         wqos_map_region2_mask                            0x03000000
#define         wqos_map_region1_offset                          20
#define         wqos_map_region1_mask                            0x00300000
#define         wqos_map_region0_offset                          16
#define         wqos_map_region0_mask                            0x00030000
#define         wqos_map_level2_offset                           8
#define         wqos_map_level2_mask                             0x00000f00
#define         wqos_map_level1_offset                           0
#define         wqos_map_level1_mask                             0x0000000f
#define     PCFGWQOS1_0                      0x4a0
#define         wqos_map_timeout2_offset                         16
#define         wqos_map_timeout2_mask                           0x07ff0000
#define         wqos_map_timeout1_offset                         0
#define         wqos_map_timeout1_mask                           0x000007ff
#define     PCFGR_1                          0x4b4
#define     PCFGW_1                          0x4b8
#define     PCTRL_1                          0x540
#define     PCFGQOS0_1                       0x544
#define     PCFGQOS1_1                       0x548
#define     PCFGWQOS0_1                      0x54c
#define     PCFGWQOS1_1                      0x550
#define     PCFGR_2                          0x564
#define     PCFGW_2                          0x568
#define     PCTRL_2                          0x5f0
#define     PCFGQOS0_2                       0x5f4
#define     PCFGQOS1_2                       0x5f8
#define     PCFGWQOS0_2                      0x5fc
#define     PCFGWQOS1_2                      0x600
#define     PCFGR_3                          0x614
#define     PCFGW_3                          0x618
#define     PCTRL_3                          0x6a0
#define     PCFGQOS0_3                       0x6a4
#define     PCFGQOS1_3                       0x6a8
#define     PCFGWQOS0_3                      0x6ac
#define     PCFGWQOS1_3                      0x6b0
#define     UMCTL2_VER_NUMBER                0xff0
#define         ver_number_offset                                0
#define         ver_number_mask                                  0xffffffff
#define     UMCTL2_VER_TYPE                  0xff4
#define         ver_type_offset                                  0
#define         ver_type_mask                                    0xffffffff
