/*
 * Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#define     ZQ0CR                            0x000
#define         Cfg_zqncr_pu_drv_code_modify_offset              28
#define         Cfg_zqncr_pu_drv_code_modify_mask                0x70000000
#define         FORCE_ZCAL_VT_UPDATE_offset                      27
#define         FORCE_ZCAL_VT_UPDATE_mask                        0x08000000
#define         IODLMT_offset                                    17
#define         IODLMT_mask                                      0x01fe0000
#define         AVGEN_offset                                     16
#define         AVGEN_mask                                       0x00010000
#define         AVGMAX_offset                                    14
#define         AVGMAX_mask                                      0x0000c000
#define         ZCALT_offset                                     11
#define         ZCALT_mask                                       0x00003800
#define         PGWAIT_offset                                    8
#define         PGWAIT_mask                                      0x00000700
#define         Cfg_zqncr_pd_drv_code_modify_offset              3
#define         Cfg_zqncr_pd_drv_code_modify_mask                0x00000038
#define         ZQPD_offset                                      2
#define         ZQPD_mask                                        0x00000004
#define         TERM_OFF_offset                                  1
#define         TERM_OFF_mask                                    0x00000002
#define     ZQ0PR                            0x004
#define         DRV_ZDEN_offset                                  31
#define         DRV_ZDEN_mask                                    0x80000000
#define         ODT_ZDEN_offset                                  30
#define         ODT_ZDEN_mask                                    0x40000000
#define         ZSEGBYP_offset                                   29
#define         ZSEGBYP_mask                                     0x20000000
#define         PU_ODT_ONLY_offset                               28
#define         PU_ODT_ONLY_mask                                 0x10000000
#define         PD_DRV_ADJUST_offset                             22
#define         PD_DRV_ADJUST_mask                               0x00c00000
#define         PU_DRV_ADJUST_offset                             20
#define         PU_DRV_ADJUST_mask                               0x00300000
#define         ZPROG_PU_ODT_ONLY_offset                         16
#define         ZPROG_PU_ODT_ONLY_mask                           0x000f0000
#define         ZPROG_ASYM_DRV_PD_offset                         12
#define         ZPROG_ASYM_DRV_PD_mask                           0x0000f000
#define         ZPROG_ASYM_DRV_PU_offset                         8
#define         ZPROG_ASYM_DRV_PU_mask                           0x00000f00
#define     ZQ0DR                            0x008
#define         zqndr_zdata_30_24_offset                         24
#define         zqndr_zdata_30_24_mask                           0x7f000000
#define         zqndr_zdata_22_16_offset                         16
#define         zqndr_zdata_22_16_mask                           0x007f0000
#define         zqndr_zdata_14_8_offset                          8
#define         zqndr_zdata_14_8_mask                            0x00007f00
#define         zqndr_zdata_6_0_offset                           0
#define         zqndr_zdata_6_0_mask                             0x0000007f
#define     ZQ0SR                            0x00c
#define         PD_DRV_SAT_offset                                11
#define         PD_DRV_SAT_mask                                  0x00000800
#define         PU_DRV_SAT_offset                                10
#define         PU_DRV_SAT_mask                                  0x00000400
#define         ZDONE_offset                                     9
#define         ZDONE_mask                                       0x00000200
#define         ZERR_offset                                      8
#define         ZERR_mask                                        0x00000100
#define         OPU_offset                                       6
#define         OPU_mask                                         0x000000c0
#define         OPD_offset                                       4
#define         OPD_mask                                         0x00000030
#define         ZPU_offset                                       2
#define         ZPU_mask                                         0x0000000c
#define         ZPD_offset                                       0
#define         ZPD_mask                                         0x00000003
#define     ZQ1CR                            0x010
#define     ZQ1PR                            0x014
#define     ZQ1DR                            0x018
#define         ZDATA_offset                                     0
#define         ZDATA_mask                                       0xffffffff
#define     ZQ1SR                            0x01c
#define     ZQ2PR                            0x024
#define     ZQ2DR                            0x028
#define     ZQ2SR                            0x02c
#define     ZQ3PR                            0x034
#define     ZQ3DR                            0x038
#define     ZQ3SR                            0x03c
#define     ZQ0VREF                          0x040
#define         Zq_vt_update_en_offset                           1
#define         Zq_vt_update_en_mask                             0x00000002
#define         ZQCALEN_offset                                   0
#define         ZQCALEN_mask                                     0x00000001
#define     WVREFSW                          0x044
#define         init_wait_cntr_offset                            16
#define         init_wait_cntr_mask                              0x03ff0000
#define         drv_to_odt_wait_cntr_offset                      8
#define         drv_to_odt_wait_cntr_mask                        0x0000ff00
#define         VREF_WAIT_CNTR_offset                            0
#define         VREF_WAIT_CNTR_mask                              0x000000ff
#define     VREF1                            0x048
#define         Vref1_ctrl_rank1_offset                          8
#define         Vref1_ctrl_rank1_mask                            0x00007f00
#define         Vref1_ctrl_rank0_offset                          0
#define         Vref1_ctrl_rank0_mask                            0x0000007f
#define     VREF2                            0x04c
#define         Vref2_ctrl_rank1_offset                          8
#define         Vref2_ctrl_rank1_mask                            0x00007f00
#define         Vref2_ctrl_rank0_offset                          0
#define         Vref2_ctrl_rank0_mask                            0x0000007f
#define     VREF3                            0x050
#define         Vref3_ctrl_rank1_offset                          8
#define         Vref3_ctrl_rank1_mask                            0x00007f00
#define         Vref3_ctrl_rank0_offset                          0
#define         Vref3_ctrl_rank0_mask                            0x0000007f
#define     VREF4                            0x054
#define         Vref4_ctrl_rank1_offset                          8
#define         Vref4_ctrl_rank1_mask                            0x00007f00
#define         Vref4_ctrl_rank0_offset                          0
#define         Vref4_ctrl_rank0_mask                            0x0000007f
#define     PZQVREF                          0x058
#define         debug_reg_sel_offset                             25
#define         debug_reg_sel_mask                               0x1e000000
#define         Vref_rg_sel_offset                               21
#define         Vref_rg_sel_mask                                 0x01e00000
#define         Vref_rk_sel_offset                               17
#define         Vref_rk_sel_mask                                 0x001e0000
#define         Vref_from_sel_offset                             16
#define         Vref_from_sel_mask                               0x00010000
#define         Vref_ctrl_pzq1_offset                            9
#define         Vref_ctrl_pzq1_mask                              0x0000fe00
#define         ddr_mode_offset                                  7
#define         ddr_mode_mask                                    0x00000080
#define         Vref_ctrl_pzq0_offset                            0
#define         Vref_ctrl_pzq0_mask                              0x0000007f
#define     DEBUG                            0x05c
#define         debug_all_offset                                 0
#define         debug_all_mask                                   0x00003fff
