image: gcc


stages:
#  - download
  - scan
  - build

#download:
#  stage: download
#  script:
#      - mkdir report

build:
  stage: build
  script:
    # run the build inside the build wrapper
    - make clean
    - make

cpp-check:
  stage: scan
  script: 
    - mkdir report
    - mkdir report/cppcheck
    - cppcheck --xml --enable=all --template=gcc --platform=unix32 . 2> report/cppcheck.xml
    - cppcheck-htmlreport --file=report/cppcheck.xml --report-dir=report/cppcheck --source-dir=.
    - ls report
  artifacts: # Save cppcheck's report
    paths:
      - report/
 # allow_failure: true
