#include "soc_plat.h"

/* all data */
/* generated by system automaticlly */
/* (1)psio data */
_UL psio_data_0[] = {
    // Config ETH0_tx_clk, PS IO 16->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_16.mc1_ensrc = 0x15
    // 0xf8803884[12:8] = 0x15
    CONFIG_REG_MASK(0xf8803884, 0x00001f00, 0x00001500),

    // Config ETH0_tx_clk, PS IO 16->Single-ended pull down Drive Strength: 16
    // register: PARA1_PS_MIO_16.mc1_ensnk = 0x17
    // 0xf8803884[20:16] = 0x17
    CONFIG_REG_MASK(0xf8803884, 0x001f0000, 0x00170000),

    // Config v, PS IO 16->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_16.mc1_i_mode = 0x2
    // 0xf8803884[1:0] = 0x2
    CONFIG_REG_MASK(0xf8803884, 0x00000003, 0x00000002),

    // Config ETH0_tx_ctl, PS IO 21->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_21.mc1_ensrc = 0x15
    // 0xf88038ac[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038ac, 0x00001f00, 0x00001500),

    // Config ETH0_tx_ctl, PS IO 21->Single-ended pull down Drive Strength: 16
    // register: PARA1_PS_MIO_21.mc1_ensnk = 0x17
    // 0xf88038ac[20:16] = 0x17
    CONFIG_REG_MASK(0xf88038ac, 0x001f0000, 0x00170000),

    // Config v, PS IO 21->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_21.mc1_i_mode = 0x2
    // 0xf88038ac[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038ac, 0x00000003, 0x00000002),

    // Config ETH0_txd3, PS IO 20->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_20.mc1_ensrc = 0x15
    // 0xf88038a4[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038a4, 0x00001f00, 0x00001500),

    // Config ETH0_txd3, PS IO 20->Single-ended pull down Drive Strength: 16
    // register: PARA1_PS_MIO_20.mc1_ensnk = 0x17
    // 0xf88038a4[20:16] = 0x17
    CONFIG_REG_MASK(0xf88038a4, 0x001f0000, 0x00170000),

    // Config v, PS IO 20->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_20.mc1_i_mode = 0x2
    // 0xf88038a4[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038a4, 0x00000003, 0x00000002),

    // Config ETH0_txd2, PS IO 19->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_19.mc1_ensrc = 0x15
    // 0xf880389c[12:8] = 0x15
    CONFIG_REG_MASK(0xf880389c, 0x00001f00, 0x00001500),

    // Config ETH0_txd2, PS IO 19->Single-ended pull down Drive Strength: 16
    // register: PARA1_PS_MIO_19.mc1_ensnk = 0x17
    // 0xf880389c[20:16] = 0x17
    CONFIG_REG_MASK(0xf880389c, 0x001f0000, 0x00170000),

    // Config v, PS IO 19->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_19.mc1_i_mode = 0x2
    // 0xf880389c[1:0] = 0x2
    CONFIG_REG_MASK(0xf880389c, 0x00000003, 0x00000002),

    // Config ETH0_txd1, PS IO 18->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_18.mc1_ensrc = 0x15
    // 0xf8803894[12:8] = 0x15
    CONFIG_REG_MASK(0xf8803894, 0x00001f00, 0x00001500),

    // Config ETH0_txd1, PS IO 18->Single-ended pull down Drive Strength: 16
    // register: PARA1_PS_MIO_18.mc1_ensnk = 0x17
    // 0xf8803894[20:16] = 0x17
    CONFIG_REG_MASK(0xf8803894, 0x001f0000, 0x00170000),

    // Config v, PS IO 18->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_18.mc1_i_mode = 0x2
    // 0xf8803894[1:0] = 0x2
    CONFIG_REG_MASK(0xf8803894, 0x00000003, 0x00000002),

    // Config ETH0_txd0, PS IO 17->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_17.mc1_ensrc = 0x15
    // 0xf880388c[12:8] = 0x15
    CONFIG_REG_MASK(0xf880388c, 0x00001f00, 0x00001500),

    // Config ETH0_txd0, PS IO 17->Single-ended pull down Drive Strength: 16
    // register: PARA1_PS_MIO_17.mc1_ensnk = 0x17
    // 0xf880388c[20:16] = 0x17
    CONFIG_REG_MASK(0xf880388c, 0x001f0000, 0x00170000),

    // Config v, PS IO 17->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_17.mc1_i_mode = 0x2
    // 0xf880388c[1:0] = 0x2
    CONFIG_REG_MASK(0xf880388c, 0x00000003, 0x00000002),

    // Config ETH0_rx_clk, PS IO 22->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_22.mc1_ensrc = 0x15
    // 0xf88038b4[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038b4, 0x00001f00, 0x00001500),

    // Config v, PS IO 22->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_22.mc1_i_mode = 0x2
    // 0xf88038b4[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038b4, 0x00000003, 0x00000002),

    // Config ETH0_rx_ctl, PS IO 27->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_27.mc1_ensrc = 0x15
    // 0xf88038dc[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038dc, 0x00001f00, 0x00001500),

    // Config v, PS IO 27->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_27.mc1_i_mode = 0x2
    // 0xf88038dc[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038dc, 0x00000003, 0x00000002),

    // Config ETH0_rxd3, PS IO 26->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_26.mc1_ensrc = 0x15
    // 0xf88038d4[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038d4, 0x00001f00, 0x00001500),

    // Config v, PS IO 26->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_26.mc1_i_mode = 0x2
    // 0xf88038d4[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038d4, 0x00000003, 0x00000002),

    // Config ETH0_rxd2, PS IO 25->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_25.mc1_ensrc = 0x15
    // 0xf88038cc[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038cc, 0x00001f00, 0x00001500),

    // Config v, PS IO 25->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_25.mc1_i_mode = 0x2
    // 0xf88038cc[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038cc, 0x00000003, 0x00000002),

    // Config ETH0_rxd1, PS IO 24->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_24.mc1_ensrc = 0x15
    // 0xf88038c4[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038c4, 0x00001f00, 0x00001500),

    // Config v, PS IO 24->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_24.mc1_i_mode = 0x2
    // 0xf88038c4[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038c4, 0x00000003, 0x00000002),

    // Config ETH0_rxd0, PS IO 23->Single-ended pull up Drive Strength: 16
    // register: PARA1_PS_MIO_23.mc1_ensrc = 0x15
    // 0xf88038bc[12:8] = 0x15
    CONFIG_REG_MASK(0xf88038bc, 0x00001f00, 0x00001500),

    // Config v, PS IO 23->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_23.mc1_i_mode = 0x2
    // 0xf88038bc[1:0] = 0x2
    CONFIG_REG_MASK(0xf88038bc, 0x00000003, 0x00000002),

    // Config ETH0_tx_clk, PS IO 16->speed: fast
    // register: PARA0_PS_MIO_16.speed = 0x7
    // 0xf8803880[2:0] = 0x7
    CONFIG_REG_MASK(0xf8803880, 0x00000007, 0x00000007),

    // Config ETH0_tx_clk, PS IO 16->PullUp: enabled
    // register: PARA0_PS_MIO_16.PullUp = 0x1
    // 0xf8803880[31:31] = 0x1
    CONFIG_REG_MASK(0xf8803880, 0x80000000, 0x80000000),

    // Config ETH0_tx_clk, PS IO 16->PullDown: enabled
    // register: PARA0_PS_MIO_16.PullDown = 0x1
    // 0xf8803880[30:30] = 0x1
    CONFIG_REG_MASK(0xf8803880, 0x40000000, 0x40000000),

    // Config ETH0_tx_ctl, PS IO 21->speed: fast
    // register: PARA0_PS_MIO_21.speed = 0x7
    // 0xf88038a8[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038a8, 0x00000007, 0x00000007),

    // Config ETH0_tx_ctl, PS IO 21->PullUp: enabled
    // register: PARA0_PS_MIO_21.PullUp = 0x1
    // 0xf88038a8[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038a8, 0x80000000, 0x80000000),

    // Config ETH0_tx_ctl, PS IO 21->PullDown: enabled
    // register: PARA0_PS_MIO_21.PullDown = 0x1
    // 0xf88038a8[30:30] = 0x1
    CONFIG_REG_MASK(0xf88038a8, 0x40000000, 0x40000000),

    // Config ETH0_txd3, PS IO 20->speed: fast
    // register: PARA0_PS_MIO_20.speed = 0x7
    // 0xf88038a0[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038a0, 0x00000007, 0x00000007),

    // Config ETH0_txd3, PS IO 20->PullUp: enabled
    // register: PARA0_PS_MIO_20.PullUp = 0x1
    // 0xf88038a0[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038a0, 0x80000000, 0x80000000),

    // Config ETH0_txd3, PS IO 20->PullDown: enabled
    // register: PARA0_PS_MIO_20.PullDown = 0x1
    // 0xf88038a0[30:30] = 0x1
    CONFIG_REG_MASK(0xf88038a0, 0x40000000, 0x40000000),

    // Config ETH0_txd2, PS IO 19->speed: fast
    // register: PARA0_PS_MIO_19.speed = 0x7
    // 0xf8803898[2:0] = 0x7
    CONFIG_REG_MASK(0xf8803898, 0x00000007, 0x00000007),

    // Config ETH0_txd2, PS IO 19->PullUp: enabled
    // register: PARA0_PS_MIO_19.PullUp = 0x1
    // 0xf8803898[31:31] = 0x1
    CONFIG_REG_MASK(0xf8803898, 0x80000000, 0x80000000),

    // Config ETH0_txd2, PS IO 19->PullDown: enabled
    // register: PARA0_PS_MIO_19.PullDown = 0x1
    // 0xf8803898[30:30] = 0x1
    CONFIG_REG_MASK(0xf8803898, 0x40000000, 0x40000000),

    // Config ETH0_txd1, PS IO 18->speed: fast
    // register: PARA0_PS_MIO_18.speed = 0x7
    // 0xf8803890[2:0] = 0x7
    CONFIG_REG_MASK(0xf8803890, 0x00000007, 0x00000007),

    // Config ETH0_txd1, PS IO 18->PullUp: enabled
    // register: PARA0_PS_MIO_18.PullUp = 0x1
    // 0xf8803890[31:31] = 0x1
    CONFIG_REG_MASK(0xf8803890, 0x80000000, 0x80000000),

    // Config ETH0_txd1, PS IO 18->PullDown: enabled
    // register: PARA0_PS_MIO_18.PullDown = 0x1
    // 0xf8803890[30:30] = 0x1
    CONFIG_REG_MASK(0xf8803890, 0x40000000, 0x40000000),

    // Config ETH0_txd0, PS IO 17->speed: fast
    // register: PARA0_PS_MIO_17.speed = 0x7
    // 0xf8803888[2:0] = 0x7
    CONFIG_REG_MASK(0xf8803888, 0x00000007, 0x00000007),

    // Config ETH0_txd0, PS IO 17->PullUp: enabled
    // register: PARA0_PS_MIO_17.PullUp = 0x1
    // 0xf8803888[31:31] = 0x1
    CONFIG_REG_MASK(0xf8803888, 0x80000000, 0x80000000),

    // Config ETH0_txd0, PS IO 17->PullDown: enabled
    // register: PARA0_PS_MIO_17.PullDown = 0x1
    // 0xf8803888[30:30] = 0x1
    CONFIG_REG_MASK(0xf8803888, 0x40000000, 0x40000000),

    // Config ETH0_rx_clk, PS IO 22->speed: fast
    // register: PARA0_PS_MIO_22.speed = 0x7
    // 0xf88038b0[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038b0, 0x00000007, 0x00000007),

    // Config ETH0_rx_clk, PS IO 22->PullUp: pullup
    // register: PARA0_PS_MIO_22.PullUp = 0x1
    // 0xf88038b0[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038b0, 0x80000000, 0x80000000),

    // Config ETH0_rx_clk, PS IO 22->PullDown: pullup
    // register: PARA0_PS_MIO_22.PullDown = 0x0
    // 0xf88038b0[30:30] = 0x0
    CONFIG_REG_MASK(0xf88038b0, 0x40000000, 0x00000000),

    // Config ETH0_rx_ctl, PS IO 27->speed: fast
    // register: PARA0_PS_MIO_27.speed = 0x7
    // 0xf88038d8[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038d8, 0x00000007, 0x00000007),

    // Config ETH0_rx_ctl, PS IO 27->PullUp: pullup
    // register: PARA0_PS_MIO_27.PullUp = 0x1
    // 0xf88038d8[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038d8, 0x80000000, 0x80000000),

    // Config ETH0_rx_ctl, PS IO 27->PullDown: pullup
    // register: PARA0_PS_MIO_27.PullDown = 0x0
    // 0xf88038d8[30:30] = 0x0
    CONFIG_REG_MASK(0xf88038d8, 0x40000000, 0x00000000),

    // Config ETH0_rxd3, PS IO 26->speed: fast
    // register: PARA0_PS_MIO_26.speed = 0x7
    // 0xf88038d0[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038d0, 0x00000007, 0x00000007),

    // Config ETH0_rxd3, PS IO 26->PullUp: pullup
    // register: PARA0_PS_MIO_26.PullUp = 0x1
    // 0xf88038d0[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038d0, 0x80000000, 0x80000000),

    // Config ETH0_rxd3, PS IO 26->PullDown: pullup
    // register: PARA0_PS_MIO_26.PullDown = 0x0
    // 0xf88038d0[30:30] = 0x0
    CONFIG_REG_MASK(0xf88038d0, 0x40000000, 0x00000000),

    // Config ETH0_rxd2, PS IO 25->speed: fast
    // register: PARA0_PS_MIO_25.speed = 0x7
    // 0xf88038c8[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038c8, 0x00000007, 0x00000007),

    // Config ETH0_rxd2, PS IO 25->PullUp: pullup
    // register: PARA0_PS_MIO_25.PullUp = 0x1
    // 0xf88038c8[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038c8, 0x80000000, 0x80000000),

    // Config ETH0_rxd2, PS IO 25->PullDown: pullup
    // register: PARA0_PS_MIO_25.PullDown = 0x0
    // 0xf88038c8[30:30] = 0x0
    CONFIG_REG_MASK(0xf88038c8, 0x40000000, 0x00000000),

    // Config ETH0_rxd1, PS IO 24->speed: fast
    // register: PARA0_PS_MIO_24.speed = 0x7
    // 0xf88038c0[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038c0, 0x00000007, 0x00000007),

    // Config ETH0_rxd1, PS IO 24->PullUp: pullup
    // register: PARA0_PS_MIO_24.PullUp = 0x1
    // 0xf88038c0[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038c0, 0x80000000, 0x80000000),

    // Config ETH0_rxd1, PS IO 24->PullDown: pullup
    // register: PARA0_PS_MIO_24.PullDown = 0x0
    // 0xf88038c0[30:30] = 0x0
    CONFIG_REG_MASK(0xf88038c0, 0x40000000, 0x00000000),

    // Config ETH0_rxd0, PS IO 23->speed: fast
    // register: PARA0_PS_MIO_23.speed = 0x7
    // 0xf88038b8[2:0] = 0x7
    CONFIG_REG_MASK(0xf88038b8, 0x00000007, 0x00000007),

    // Config ETH0_rxd0, PS IO 23->PullUp: pullup
    // register: PARA0_PS_MIO_23.PullUp = 0x1
    // 0xf88038b8[31:31] = 0x1
    CONFIG_REG_MASK(0xf88038b8, 0x80000000, 0x80000000),

    // Config ETH0_rxd0, PS IO 23->PullDown: pullup
    // register: PARA0_PS_MIO_23.PullDown = 0x0
    // 0xf88038b8[30:30] = 0x0
    CONFIG_REG_MASK(0xf88038b8, 0x40000000, 0x00000000),

    // Config ETH0, PS IO 16->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_16.funcsel_ps_mio_16 = 14
    // 0xf8803040[3:0] = 14
    CONFIG_REG_MASK(0xf8803040, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 21->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_21.funcsel_ps_mio_21 = 14
    // 0xf8803054[3:0] = 14
    CONFIG_REG_MASK(0xf8803054, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 20->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_20.funcsel_ps_mio_20 = 14
    // 0xf8803050[3:0] = 14
    CONFIG_REG_MASK(0xf8803050, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 19->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_19.funcsel_ps_mio_19 = 14
    // 0xf880304c[3:0] = 14
    CONFIG_REG_MASK(0xf880304c, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 18->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_18.funcsel_ps_mio_18 = 14
    // 0xf8803048[3:0] = 14
    CONFIG_REG_MASK(0xf8803048, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 17->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_17.funcsel_ps_mio_17 = 14
    // 0xf8803044[3:0] = 14
    CONFIG_REG_MASK(0xf8803044, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 22->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_22.funcsel_ps_mio_22 = 14
    // 0xf8803058[3:0] = 14
    CONFIG_REG_MASK(0xf8803058, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 27->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_27.funcsel_ps_mio_27 = 14
    // 0xf880306c[3:0] = 14
    CONFIG_REG_MASK(0xf880306c, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 26->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_26.funcsel_ps_mio_26 = 14
    // 0xf8803068[3:0] = 14
    CONFIG_REG_MASK(0xf8803068, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 25->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_25.funcsel_ps_mio_25 = 14
    // 0xf8803064[3:0] = 14
    CONFIG_REG_MASK(0xf8803064, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 24->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_24.funcsel_ps_mio_24 = 14
    // 0xf8803060[3:0] = 14
    CONFIG_REG_MASK(0xf8803060, 0x0000000f, 0x0000000e),

    // Config ETH0, PS IO 23->FUNCSEL: ETH0
    // register: FUNCSEL_PS_MIO_23.funcsel_ps_mio_23 = 14
    // 0xf880305c[3:0] = 14
    CONFIG_REG_MASK(0xf880305c, 0x0000000f, 0x0000000e),

    // Config ETH0_mdc, PS IO 52->Single-ended pull up Drive Strength: 8
    // register: PARA1_PS_MIO_52.mc1_ensrc = 0x06
    // 0xf88039a4[12:8] = 0x06
    CONFIG_REG_MASK(0xf88039a4, 0x00001f00, 0x00000600),

    // Config v, PS IO 52->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_52.mc1_i_mode = 0x2
    // 0xf88039a4[1:0] = 0x2
    CONFIG_REG_MASK(0xf88039a4, 0x00000003, 0x00000002),

    // Config ETH0_mdio, PS IO 53->Single-ended pull up Drive Strength: 8
    // register: PARA1_PS_MIO_53.mc1_ensrc = 0x06
    // 0xf88039ac[12:8] = 0x06
    CONFIG_REG_MASK(0xf88039ac, 0x00001f00, 0x00000600),

    // Config v, PS IO 53->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_53.mc1_i_mode = 0x2
    // 0xf88039ac[1:0] = 0x2
    CONFIG_REG_MASK(0xf88039ac, 0x00000003, 0x00000002),

    // Config ETH0_mdc, PS IO 52->speed: medium
    // register: PARA0_PS_MIO_52.speed = 0x2
    // 0xf88039a0[2:0] = 0x2
    CONFIG_REG_MASK(0xf88039a0, 0x00000007, 0x00000002),

    // Config ETH0_mdc, PS IO 52->PullUp: pullup
    // register: PARA0_PS_MIO_52.PullUp = 0x1
    // 0xf88039a0[31:31] = 0x1
    CONFIG_REG_MASK(0xf88039a0, 0x80000000, 0x80000000),

    // Config ETH0_mdc, PS IO 52->PullDown: pullup
    // register: PARA0_PS_MIO_52.PullDown = 0x0
    // 0xf88039a0[30:30] = 0x0
    CONFIG_REG_MASK(0xf88039a0, 0x40000000, 0x00000000),

    // Config ETH0_mdio, PS IO 53->speed: medium
    // register: PARA0_PS_MIO_53.speed = 0x2
    // 0xf88039a8[2:0] = 0x2
    CONFIG_REG_MASK(0xf88039a8, 0x00000007, 0x00000002),

    // Config ETH0_mdio, PS IO 53->PullUp: pullup
    // register: PARA0_PS_MIO_53.PullUp = 0x1
    // 0xf88039a8[31:31] = 0x1
    CONFIG_REG_MASK(0xf88039a8, 0x80000000, 0x80000000),

    // Config ETH0_mdio, PS IO 53->PullDown: pullup
    // register: PARA0_PS_MIO_53.PullDown = 0x0
    // 0xf88039a8[30:30] = 0x0
    CONFIG_REG_MASK(0xf88039a8, 0x40000000, 0x00000000),

    // Config MDIO0, PS IO 52->FUNCSEL: MDIO0
    // register: FUNCSEL_PS_MIO_52.funcsel_ps_mio_52 = 14
    // 0xf88030d0[3:0] = 14
    CONFIG_REG_MASK(0xf88030d0, 0x0000000f, 0x0000000e),

    // Config MDIO0, PS IO 53->FUNCSEL: MDIO0
    // register: FUNCSEL_PS_MIO_53.funcsel_ps_mio_53 = 14
    // 0xf88030d4[3:0] = 14
    CONFIG_REG_MASK(0xf88030d4, 0x0000000f, 0x0000000e),

    // Config MDIO0, Select IO: "PS IO 52...53", config emio
    // register: EMIOSEL_13.emiosel_13 = 1
    // 0xF8803434[0:0] = 1
    CONFIG_REG_MASK(0xF8803434, 0x00000001, 0x00000001),

    // Config UART1_tx, PS IO 48->Single-ended pull up Drive Strength: 8
    // register: PARA1_PS_MIO_48.mc1_ensrc = 0x06
    // 0xf8803984[12:8] = 0x06
    CONFIG_REG_MASK(0xf8803984, 0x00001f00, 0x00000600),

    // Config v, PS IO 48->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_48.mc1_i_mode = 0x2
    // 0xf8803984[1:0] = 0x2
    CONFIG_REG_MASK(0xf8803984, 0x00000003, 0x00000002),

    // Config UART1_rx, PS IO 49->Single-ended pull up Drive Strength: 8
    // register: PARA1_PS_MIO_49.mc1_ensrc = 0x06
    // 0xf880398c[12:8] = 0x06
    CONFIG_REG_MASK(0xf880398c, 0x00001f00, 0x00000600),

    // Config v, PS IO 49->mc1_i_mode: LVCMOS 1.8V
    // register: PARA1_PS_MIO_49.mc1_i_mode = 0x2
    // 0xf880398c[1:0] = 0x2
    CONFIG_REG_MASK(0xf880398c, 0x00000003, 0x00000002),

    // Config UART1_tx, PS IO 48->speed: slow
    // register: PARA0_PS_MIO_48.speed = 0x0
    // 0xf8803980[2:0] = 0x0
    CONFIG_REG_MASK(0xf8803980, 0x00000007, 0x00000000),

    // Config UART1_tx, PS IO 48->PullUp: pullup
    // register: PARA0_PS_MIO_48.PullUp = 0x1
    // 0xf8803980[31:31] = 0x1
    CONFIG_REG_MASK(0xf8803980, 0x80000000, 0x80000000),

    // Config UART1_tx, PS IO 48->PullDown: pullup
    // register: PARA0_PS_MIO_48.PullDown = 0x0
    // 0xf8803980[30:30] = 0x0
    CONFIG_REG_MASK(0xf8803980, 0x40000000, 0x00000000),

    // Config UART1_rx, PS IO 49->speed: slow
    // register: PARA0_PS_MIO_49.speed = 0x0
    // 0xf8803988[2:0] = 0x0
    CONFIG_REG_MASK(0xf8803988, 0x00000007, 0x00000000),

    // Config UART1_rx, PS IO 49->PullUp: pullup
    // register: PARA0_PS_MIO_49.PullUp = 0x1
    // 0xf8803988[31:31] = 0x1
    CONFIG_REG_MASK(0xf8803988, 0x80000000, 0x80000000),

    // Config UART1_rx, PS IO 49->PullDown: pullup
    // register: PARA0_PS_MIO_49.PullDown = 0x0
    // 0xf8803988[30:30] = 0x0
    CONFIG_REG_MASK(0xf8803988, 0x40000000, 0x00000000),

    // Config UART1, PS IO 48->FUNCSEL: UART1
    // register: FUNCSEL_PS_MIO_48.funcsel_ps_mio_48 = 3
    // 0xf88030c0[3:0] = 3
    CONFIG_REG_MASK(0xf88030c0, 0x0000000f, 0x00000003),

    // Config UART1, PS IO 49->FUNCSEL: UART1
    // register: FUNCSEL_PS_MIO_49.funcsel_ps_mio_49 = 3
    // 0xf88030c4[3:0] = 3
    CONFIG_REG_MASK(0xf88030c4, 0x0000000f, 0x00000003),

    // Config UART1, Select IO: "PS IO 48...49", config emio
    // register: EMIOSEL_5.emiosel_5 = 1
    // 0xF8803414[0:0] = 1
    CONFIG_REG_MASK(0xF8803414, 0x00000001, 0x00000001),

    /* configuration complete */
    CONFIG_REG_EXIT()
};

/* (2) clock data */
/* pll initialization flow:  
**      a: pll bypass,
**      b: config clock frequency dividing ratio: 6:2:1, 4:2:1,2:2:1
**      c: config cpu pll divider and io pll divider
**      d: wait for cpu pll and io pll locking
**      e: pll enable
*/
_UL clk_data_0[] = {
    // Config clock source, cpu clock source : OSC CLK, pll bypass
    // register: CLK_SEL.slow_sel = 1
    // 0xF8801040[4:4] = 1
    CONFIG_REG_MASK(0xF8801040, 0x00000010, 0x00000010),

    // Config CRG_EN, cpu 4x div1: 4:2:1
    // register: CPU4X_DIV1_PARA.cpu4x_div1_para = 0xffffff
    // 0xF8801010[23:0] = 0xffffff
    CONFIG_REG_MASK(0xF8801010, 0x00ffffff, 0x00ffffff),

    // Config CRG_EN, cpu 4x div2: 4:2:1
    // register: CPU4X_DIV2_PARA.cpu4x_div2_para = 0x555555
    // 0xF8801014[23:0] = 0x555555
    CONFIG_REG_MASK(0xF8801014, 0x00ffffff, 0x00555555),

    // Config CRG_EN, cpu 4x div4: 4:2:1
    // register: CPU4X_DIV4_PARA.cpu4x_div4_para = 0x111111
    // 0xF8801018[23:0] = 0x111111
    CONFIG_REG_MASK(0xF8801018, 0x00ffffff, 0x00111111),

    // Config clock source, cpu clock ratio : cpu6x4x_sel = 0
    // register: CLK_SEL.cpu6x4x_sel = 0
    // 0xF8801040[0:0] = 0
    CONFIG_REG_MASK(0xF8801040, 0x00000001, 0x00000000),

    // Config clock source, rpu core clock selection: 4:2:1
    // register: CLK_SEL.rpu4x2x_sel = 0x0
    // 0xF8801040[5:5] = 0x0
    CONFIG_REG_MASK(0xF8801040, 0x00000020, 0x00000000),

    // Config CPUPLL, cpu pll reset
    // register: CPUPLL_CTRL1.ctrl1_cpupll = 1
    // 0xF8801104[9:9] = 1
    CONFIG_REG_MASK(0xF8801104, 0x00000200, 0x00000200),

    // Config CPUPLL, CPU N: 108, mc1_fbk_div: 107
    // register: CPUPLL_CTRL9.ctrl9_cpupll = 0x0000006b
    // 0xF8801124[6:0] = 0x0000006b
    CONFIG_REG_MASK(0xF8801124, 0x0000007f, 0x0000006b),

    // Config CPUPLL, mc1_kvco_sel: 0
    // register: CPUPLL_CTRL9.ctrl9_cpupll = 0x00000000
    // 0xF8801124[13:12] = 0x00000000
    CONFIG_REG_MASK(0xF8801124, 0x00003000, 0x00000000),

    // Config CPUPLL, mc1_gm_prog: 1
    // register: CPUPLL_CTRL9.ctrl9_cpupll = 0x00000001
    // 0xF8801124[26:24] = 0x00000001
    CONFIG_REG_MASK(0xF8801124, 0x07000000, 0x01000000),

    // Config CPUPLL, CPU M: 2, mc1_ref_div: 1
    // register: CPUPLL_CTRL8.ctrl8_cpupll = 0x00000001
    // 0xF8801120[6:0] = 0x00000001
    CONFIG_REG_MASK(0xF8801120, 0x0000007f, 0x00000001),

    // Config CPUPLL, mc1_icp_sel: 10
    // register: CPUPLL_CTRL8.ctrl8_cpupll = 0x0000000a
    // 0xF8801120[20:16] = 0x0000000a
    CONFIG_REG_MASK(0xF8801120, 0x001f0000, 0x000a0000),

    // Config CPUPLL, mc1_lpf_cap: 2
    // register: CPUPLL_CTRL8.ctrl8_cpupll = 0x00000002
    // 0xF8801120[27:26] = 0x00000002
    CONFIG_REG_MASK(0xF8801120, 0x0c000000, 0x08000000),

    // Config CPUPLL, mc1_lpf_res: 4
    // register: CPUPLL_CTRL8.ctrl8_cpupll = 0x00000004
    // 0xF8801120[30:28] = 0x00000004
    CONFIG_REG_MASK(0xF8801120, 0x70000000, 0x40000000),

    // Config CPUPLL, CPU C: 2, mc1_divc1: 1
    // register: CPUPLL_CTRL19.ctrl19_cpupll = 0x00000001
    // 0xF880114C[30:24] = 0x00000001
    CONFIG_REG_MASK(0xF880114C, 0x7f000000, 0x01000000),

    // Config CPUPLL, CPU C: 2, mc1_duty1: 1
    // register: CPUPLL_CTRL19.ctrl19_cpupll = 0x00000001
    // 0xF880114C[6:0] = 0x00000001
    CONFIG_REG_MASK(0xF880114C, 0x0000007f, 0x00000001),

    // Config CPUPLL, CPU C: 2, mc1_divc0: 1
    // register: CPUPLL_CTRL18.ctrl18_cpupll = 0x00000001
    // 0xF8801148[30:24] = 0x00000001
    CONFIG_REG_MASK(0xF8801148, 0x7f000000, 0x01000000),

    // Config CPUPLL, CPU C: 2, mc1_duty0: 1
    // register: CPUPLL_CTRL18.ctrl18_cpupll = 0x00000001
    // 0xF8801148[6:0] = 0x00000001
    CONFIG_REG_MASK(0xF8801148, 0x0000007f, 0x00000001),

    // Config CPUPLL, cpu pll release
    // register: CPUPLL_CTRL1.ctrl1_cpupll = 0
    // 0xF8801104[9:9] = 0
    CONFIG_REG_MASK(0xF8801104, 0x00000200, 0x00000000),

    // Config IOPLL, io pll reset
    // register: IOPLL_CTRL1.ctrl1_iopll = 1
    // 0xF8801204[9:9] = 1
    CONFIG_REG_MASK(0xF8801204, 0x00000200, 0x00000200),

    // Config IOPLL, IO N: 120, mc1_fbk_div: 119
    // register: IOPLL_CTRL9.ctrl9_iopll = 0x00000077
    // 0xF8801224[6:0] = 0x00000077
    CONFIG_REG_MASK(0xF8801224, 0x0000007f, 0x00000077),

    // Config IOPLL, mc1_kvco_sel: 0
    // register: IOPLL_CTRL9.ctrl9_iopll = 0x00000000
    // 0xF8801224[13:12] = 0x00000000
    CONFIG_REG_MASK(0xF8801224, 0x00003000, 0x00000000),

    // Config IOPLL, mc1_gm_prog: 1
    // register: IOPLL_CTRL9.ctrl9_iopll = 0x00000001
    // 0xF8801224[26:24] = 0x00000001
    CONFIG_REG_MASK(0xF8801224, 0x07000000, 0x01000000),

    // Config IOPLL, IO M: 2, mc1_ref_div: 1
    // register: IOPLL_CTRL8.ctrl8_iopll = 0x00000001
    // 0xF8801220[6:0] = 0x00000001
    CONFIG_REG_MASK(0xF8801220, 0x0000007f, 0x00000001),

    // Config IOPLL, mc1_icp_sel: 10
    // register: IOPLL_CTRL8.ctrl8_iopll = 0x0000000a
    // 0xF8801220[20:16] = 0x0000000a
    CONFIG_REG_MASK(0xF8801220, 0x001f0000, 0x000a0000),

    // Config IOPLL, mc1_lpf_cap: 2
    // register: IOPLL_CTRL8.ctrl8_iopll = 0x00000002
    // 0xF8801220[27:26] = 0x00000002
    CONFIG_REG_MASK(0xF8801220, 0x0c000000, 0x08000000),

    // Config IOPLL, mc1_lpf_res: 4
    // register: IOPLL_CTRL8.ctrl8_iopll = 0x00000004
    // 0xF8801220[30:28] = 0x00000004
    CONFIG_REG_MASK(0xF8801220, 0x70000000, 0x40000000),

    // Config IOPLL, IO1000 C: 2, mc1_divc0: 1
    // register: IOPLL_CTRL18.ctrl18_iopll = 0x00000001
    // 0xF8801248[30:24] = 0x00000001
    CONFIG_REG_MASK(0xF8801248, 0x7f000000, 0x01000000),

    // Config IOPLL, IO1000 C: 2, mc1_duty0: 1
    // register: IOPLL_CTRL18.ctrl18_iopll = 0x00000001
    // 0xF8801248[6:0] = 0x00000001
    CONFIG_REG_MASK(0xF8801248, 0x0000007f, 0x00000001),

    // Config IOPLL, IO400 C: 5, mc1_divc1: 4
    // register: IOPLL_CTRL19.ctrl19_iopll = 0x00000004
    // 0xF880124c[30:24] = 0x00000004
    CONFIG_REG_MASK(0xF880124c, 0x7f000000, 0x04000000),

    // Config IOPLL, IO400 C: 5, mc1_duty1: 3
    // register: IOPLL_CTRL19.ctrl19_iopll = 0x00000003
    // 0xF880124c[6:0] = 0x00000003
    CONFIG_REG_MASK(0xF880124c, 0x0000007f, 0x00000003),

    // Config IOPLL, IO1000 C: 80, mc1_divc2: 79
    // register: IOPLL_CTRL20.ctrl20_iopll = 0x0000004f
    // 0xF8801250[30:24] = 0x0000004f
    CONFIG_REG_MASK(0xF8801250, 0x7f000000, 0x4f000000),

    // Config IOPLL, IO1000 C: 80, mc1_duty2: 40
    // register: IOPLL_CTRL20.ctrl20_iopll = 0x00000028
    // 0xF8801250[6:0] = 0x00000028
    CONFIG_REG_MASK(0xF8801250, 0x0000007f, 0x00000028),

    // Config IOPLL, IO400 C: 25, mc1_divc3: 24
    // register: IOPLL_CTRL21.ctrl21_iopll = 0x00000018
    // 0xF8801254[30:24] = 0x00000018
    CONFIG_REG_MASK(0xF8801254, 0x7f000000, 0x18000000),

    // Config IOPLL, IO400 C: 25, mc1_duty3: 13
    // register: IOPLL_CTRL21.ctrl21_iopll = 0x0000000d
    // 0xF8801254[6:0] = 0x0000000d
    CONFIG_REG_MASK(0xF8801254, 0x0000007f, 0x0000000d),

    // Config IOPLL, io pll release
    // register: IOPLL_CTRL1.ctrl1_iopll = 0
    // 0xF8801204[9:9] = 0
    CONFIG_REG_MASK(0xF8801204, 0x00000200, 0x00000000),

    // Config CPUPLL, CPU PLL WaitLock
    // register: CPUPLL_STATE0.state0_cpupll = 1
    // 0xF8801180[0:0] = 1
    CONFIG_REG_MASKPOLL(0xF8801180, 0x00000001, 0x00000001),

    // Config IOPLL, IO PLL WaitLock
    // register: IOPLL_STATE0.state0_iopll = 1
    // 0xF8801280[0:0] = 1
    CONFIG_REG_MASKPOLL(0xF8801280, 0x00000001, 0x00000001),

    // Config clock source, cpu clock source : PLL CLK, pll enable
    // register: CLK_SEL.slow_sel = 0
    // 0xF8801040[4:4] = 0
    CONFIG_REG_MASK(0xF8801040, 0x00000010, 0x00000000),

    // Config p2f_clk0, system div para for fclk0: 8, based on IO400
    // register: FCLK_CNT_DIV.div_fclk0 = 0x00000007
    // 0xF880103C[5:0] = 0x00000007
    CONFIG_REG_MASK(0xF880103C, 0x0000003f, 0x00000007),

    /* configuration complete */
    CONFIG_REG_EXIT()
};

/* (3) ps_pl data */
_UL ps_pl_0[] = {
    /* configuration complete */
    CONFIG_REG_EXIT()
};

/* (4) ddr data */
_UL ddr_data_0[] = {
    /* configuration complete */
    CONFIG_REG_EXIT()
};

/* (5) peripherals data */
_UL peripherals_data_0[] = {
    /* configuration complete */
    CONFIG_REG_EXIT()
};

/* (6) debug data */
_UL debug_data_0[] = {
    /* configuration complete */
    CONFIG_REG_EXIT()
};

/* (7) system data */
_UL system_data_0[] = {
    // Config JTAG, ARM TAP dummy
    // register: JTAG_CTRL.arm_tap_off = 0x1
    // 0xF88060A8[3:3] = 0x1
    CONFIG_REG_MASK(0xF88060A8, 0x00000008, 0x00000008),

    // Config pin, fix to LVCMOS 1.8V
    // register: IO_BANK200_REF.bank200_mc1_force_dtc = 0x1
    // 0xF8803c00[5:4] = 0x1
    CONFIG_REG_MASK(0xF8803c00, 0x00000030, 0x00000010),

    // Config pin, fix to LVCMOS 1.8V
    // register: IO_BANK201_REF.bank201_mc1_force_dtc = 0x1
    // 0xF8803c04[5:4] = 0x1
    CONFIG_REG_MASK(0xF8803c04, 0x00000030, 0x00000010),

    /* configuration complete */
    CONFIG_REG_EXIT()
};

static int __attribute__ ((optimize(0))) __plat_config(_UL *config_data) 
{
    _UL *ptr = config_data;
    _UL  config_code;     /* current instruction */
    _UL  args[16];        /* config_code args: max 16 */
    int numargs;          /* number of arguments of this instruction */
    int j;                /* general purpose index */

    volatile _UL *_addr;  /* config addr */
    _UL  _value,_mask;    /* config value and mask */

    int finish = -1 ;           
    int i = 0;                
    
    while( finish < 0 ) {
        /* parser op code */
        numargs = ptr[0] & 0xF;
        config_code = ptr[0] >> 4;
        for( j = 0 ; j < numargs ; j ++ ) 
            args[j] = ptr[j+1];
        ptr += numargs + 1;
        
        /* write data to addr */
        switch (config_code) {
        case CONFIG_EXIT:
            finish = PLAT_INIT_SUCCESS;
            break;
            
        case CONFIG_CLEAR:
            _addr = (_UL*) args[0];
            *_addr = 0;
            break;

        case CONFIG_WRITE:
            _addr  = (_UL*) args[0];
            _value = args[1];
            *_addr = _value;
            break;

        case CONFIG_MASKWRITE:
            _addr  = (_UL*) args[0];
            _mask  = args[1];
            _value = args[2];
            *_addr = ( _value & _mask ) | ( *_addr & ~_mask);
            break;
        case CONFIG_MASKPOLL:
            _addr = (_UL*) args[0];
            _mask = args[1];
            _value = args[2];
            i = 0;
            while (_value != (*_addr & _mask)) {
                if (i == CONFIG_POLL_TIME) {
                    finish = PLAT_INIT_TIMEOUT;
                    break;
                }
                i++;
            }
            break;
            
        default:
            finish = PLAT_INIT_OPCODE_ERROR;
            break;
	    }
    }
    return finish;
}

#ifdef USE_DDR_DEBUG
extern int  fd_ddr_init();
#endif

int Soc_PlatInit() 
{
    int rtn = 0;
    _UL *config_data;
    _UL device_version = Soc_PlatGetDeviceVersion();
    if (device_version == SOC_VERSION_1) {
        /* device version 0.1 */

        /* (0) config system data */
        config_data = system_data_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;

        /* (1) config psio */
        config_data = psio_data_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;
        
        /* (2) config clock */
        config_data = clk_data_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;

         /* (3) config ps_pl */
        config_data = ps_pl_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;

#ifdef USE_DDR_DEBUG
        fd_ddr_init();
#else
        /* (4) config ddr */
        config_data = ddr_data_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;
#endif
        
        /* (5) config peripherals */
        config_data = peripherals_data_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;

        /* (6) config debug data*/
        config_data = debug_data_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS) 
            return rtn;
        
    } else {
        return PLAT_INIT_VERSION_ERROR;
    }
    return PLAT_INIT_SUCCESS;  
}

int Soc_PsPlInit()
{
    int rtn = 0;
    _UL *config_data;
    _UL device_version = Soc_PlatGetDeviceVersion();
    if (device_version == SOC_VERSION_1) {
        /* (1) config ps_pl */
        config_data = ps_pl_0;
        rtn = __plat_config(config_data);
        if (rtn != PLAT_INIT_SUCCESS)
            return rtn;
    } else {
        return PLAT_INIT_VERSION_ERROR;
    }
    return PLAT_INIT_SUCCESS;
}

int Soc_PlatGetDeviceVersion () 
{
    return SOC_VERSION_1;
}


