/*
 * This file will be generated by FD
*/

#ifndef __AL_PARAMS__
#define __AL_PARAMS__

#ifdef __cplusplus
extern "C" {
#endif

#define __ECLIC_PRESENT           1                     /*!< Set to 1 if ECLIC is present */
#define __SYSTIMER_PRESENT        1                     /*!< Set to 1 if System Timer is present */


/*!< Set to 0, 1, or 2, 0 not present, 1 single floating point unit present, 2 double floating point unit present */
#if !defined(__riscv_flen)
#define __FPU_PRESENT             0
#elif __riscv_flen == 32
#define __FPU_PRESENT             1
#else
#define __FPU_PRESENT             2
#endif

#define __PMP_PRESENT             1                     /*!< Set to 1 if PMP is present */
#define __PMP_ENTRY_NUM           16                    /*!< Set to 8 or 16, the number of PMP entries */
#define __ICACHE_PRESENT          0                     /*!< Set to 1 if I-Cache is present */
#define __DCACHE_PRESENT          0                     /*!< Set to 1 if D-Cache is present */

#define __ECLIC_BASEADDR        (0x68000000UL)            /*!< Set to ECLIC baseaddr of your device */
#define __SYSTIMER_BASEADDR     (0x68020000UL)            /*!< Set to SysTimer baseaddr of your device */

typedef enum {
    SysTimer_IRQn        =  7,
    GPIO0_IRQn           =  71,
    SOC_INT130_IRQn      =  130,
    SOC_INT89_IRQn       =  89,
    SOC_INT_MAX          =  256,
};

/*----------------------------------------------------------------------------
  Define clocks
 *----------------------------------------------------------------------------*/
#ifndef SYSTEM_CLOCK
#define SYSTEM_CLOCK           (50000000UL)
#endif


#ifdef __cplusplus
}
#endif

#endif  /* __AL_PARAMS__ */
