TARGET = al_9000_aximon


NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = . src ./../../demo_dmac_axi/dmac_axi_driver

INCDIRS = . inc ./../../demo_dmac_axi/dmac_axi_driver


#COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
