#define     CLK_SEL                          0x000
#define         ddrslow_sel_offset                               0
#define         ddrslow_sel_mask                                 0x00000001
#define     SRST_CTRL                        0x004
#define         ddrc_srst_n_offset                               0
#define         ddrc_srst_n_mask                                 0x00000001
#define     FUNCTRL                          0x008
#define         dfi_data_mapping_ecc_mode_sel_offset             1
#define         dfi_data_mapping_ecc_mode_sel_mask               0x0000000e
#define         dis_regs_ecc_syndrome_offset                     0
#define         dis_regs_ecc_syndrome_mask                       0x00000001
#define     TPARA_SP_CPU2X                   0x010
#define         tpara_sp_ddr_offset                              0
#define         tpara_sp_ddr_mask                                0xffffffff
#define     DDRGPLL_CTRL0                    0x100
#define         ctrl0_ddrgpll_offset                             0
#define         ctrl0_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL1                    0x104
#define         ctrl1_pllreset_offset                            9
#define         ctrl1_pllreset_mask                              0x00000200
#define     DDRGPLL_CTRL2                    0x108
#define         ctrl2_ddrgpll_offset                             0
#define         ctrl2_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL3                    0x10C
#define         ctrl3_ddrgpll_offset                             0
#define         ctrl3_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL4                    0x110
#define         ctrl4_ddrgpll_offset                             0
#define         ctrl4_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL5                    0x114
#define         ctrl5_ddrgpll_offset                             0
#define         ctrl5_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL6                    0x118
#define         ctrl6_ddrgpll_offset                             0
#define         ctrl6_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL7                    0x11C
#define         ctrl7_ddrgpll_offset                             0
#define         ctrl7_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL8                    0x120
#define         ctrl8_ddrgpll_offset                             0
#define         ctrl8_ddrgpll_mask                               0xffffffff
#define     DDRGPLL_CTRL9                    0x124
#define         ctrl9_fbk_div_offset                             0
#define         ctrl9_fbk_div_mask                               0x0000007f
#define     DDRGPLL_CTRL10                   0x128
#define         ctrl10_ddrgpll_offset                            0
#define         ctrl10_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL11                   0x12C
#define         ctrl11_ddrgpll_offset                            0
#define         ctrl11_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL12                   0x130
#define         ctrl12_ddrgpll_offset                            0
#define         ctrl12_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL13                   0x134
#define         ctrl13_ddrgpll_offset                            0
#define         ctrl13_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL14                   0x138
#define         ctrl14_ddrgpll_offset                            0
#define         ctrl14_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL15                   0x13C
#define         ctrl15_ddrgpll_offset                            0
#define         ctrl15_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL16                   0x140
#define         ctrl16_ddrgpll_offset                            0
#define         ctrl16_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL17                   0x144
#define         ctrl17_ddrgpll_offset                            0
#define         ctrl17_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL18                   0x148
#define     DDRGPLL_CTRL19                   0x14C
#define     DDRGPLL_CTRL20                   0x150
#define     DDRGPLL_CTRL21                   0x154
#define     DDRGPLL_CTRL22                   0x158
#define     DDRGPLL_CTRL23                   0x15C
#define     DDRGPLL_CTRL24                   0x160
#define         gpll_duty_offset                                 0
#define         gpll_duty_mask                                   0x0000007f
#define         gpll_dyn_delc_offset                             8
#define         gpll_dyn_delc_mask                               0x00007f00
#define         gpll_delc_offset                                 16
#define         gpll_delc_mask                                   0x007f0000
#define         gpll_divc_offset                                 24
#define         gpll_divc_mask                                   0x7f000000
#define     DDRGPLL_CTRL25                   0x164
#define         ctrl25_ddrgpll_offset                            0
#define         ctrl25_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_CTRL26                   0x168
#define         ctrl26_ddrgpll_offset                            0
#define         ctrl26_ddrgpll_mask                              0xffffffff
#define     DDRGPLL_STATE0                   0x180
#define         gpll_lock_offset                                 0
#define         gpll_lock_mask                                   0x00000001
#define     BK0_T01_MATRIX_CTRL              0x184
#define         BK0_IS_AC_offset                                 0
#define         BK0_IS_AC_mask                                   0x00000001
#define     AC_BANK_MTX_CR0                  0x188
#define         AC_BANK_MTX_IO4_SEL_offset                       24
#define         AC_BANK_MTX_IO4_SEL_mask                         0x3f000000
#define         AC_BANK_MTX_IO3_SEL_offset                       18
#define         AC_BANK_MTX_IO3_SEL_mask                         0x00fc0000
#define         AC_BANK_MTX_IO2_SEL_offset                       12
#define         AC_BANK_MTX_IO2_SEL_mask                         0x0003f000
#define         AC_BANK_MTX_IO1_SEL_offset                       6
#define         AC_BANK_MTX_IO1_SEL_mask                         0x00000fc0
#define         AC_BANK_MTX_IO0_SEL_offset                       0
#define         AC_BANK_MTX_IO0_SEL_mask                         0x0000003f
#define     AC_BANK_MTX_CR1                  0x18c
#define         AC_BANK_MTX_IO9_SEL_offset                       24
#define         AC_BANK_MTX_IO9_SEL_mask                         0x3f000000
#define         AC_BANK_MTX_IO8_SEL_offset                       18
#define         AC_BANK_MTX_IO8_SEL_mask                         0x00fc0000
#define         AC_BANK_MTX_IO7_SEL_offset                       12
#define         AC_BANK_MTX_IO7_SEL_mask                         0x0003f000
#define         AC_BANK_MTX_IO6_SEL_offset                       6
#define         AC_BANK_MTX_IO6_SEL_mask                         0x00000fc0
#define         AC_BANK_MTX_IO5_SEL_offset                       0
#define         AC_BANK_MTX_IO5_SEL_mask                         0x0000003f
#define     AC_BANK_MTX_CR2                  0x190
#define         AC_BANK_MTX_IO14_SEL_offset                      24
#define         AC_BANK_MTX_IO14_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO13_SEL_offset                      18
#define         AC_BANK_MTX_IO13_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO12_SEL_offset                      12
#define         AC_BANK_MTX_IO12_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO11_SEL_offset                      6
#define         AC_BANK_MTX_IO11_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO10_SEL_offset                      0
#define         AC_BANK_MTX_IO10_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR3                  0x194
#define         AC_BANK_MTX_IO19_SEL_offset                      24
#define         AC_BANK_MTX_IO19_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO18_SEL_offset                      18
#define         AC_BANK_MTX_IO18_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO17_SEL_offset                      12
#define         AC_BANK_MTX_IO17_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO16_SEL_offset                      6
#define         AC_BANK_MTX_IO16_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO15_SEL_offset                      0
#define         AC_BANK_MTX_IO15_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR4                  0x198
#define         AC_BANK_MTX_IO24_SEL_offset                      24
#define         AC_BANK_MTX_IO24_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO23_SEL_offset                      18
#define         AC_BANK_MTX_IO23_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO22_SEL_offset                      12
#define         AC_BANK_MTX_IO22_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO21_SEL_offset                      6
#define         AC_BANK_MTX_IO21_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO20_SEL_offset                      0
#define         AC_BANK_MTX_IO20_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR5                  0x19c
#define         AC_BANK_MTX_IO29_SEL_offset                      24
#define         AC_BANK_MTX_IO29_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO28_SEL_offset                      18
#define         AC_BANK_MTX_IO28_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO27_SEL_offset                      12
#define         AC_BANK_MTX_IO27_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO26_SEL_offset                      6
#define         AC_BANK_MTX_IO26_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO25_SEL_offset                      0
#define         AC_BANK_MTX_IO25_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR6                  0x1a0
#define         AC_BANK_MTX_IO34_SEL_offset                      24
#define         AC_BANK_MTX_IO34_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO33_SEL_offset                      18
#define         AC_BANK_MTX_IO33_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO32_SEL_offset                      12
#define         AC_BANK_MTX_IO32_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO31_SEL_offset                      6
#define         AC_BANK_MTX_IO31_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO30_SEL_offset                      0
#define         AC_BANK_MTX_IO30_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR7                  0x1a4
#define         AC_BANK_MTX_IO39_SEL_offset                      24
#define         AC_BANK_MTX_IO39_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO38_SEL_offset                      18
#define         AC_BANK_MTX_IO38_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO37_SEL_offset                      12
#define         AC_BANK_MTX_IO37_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO36_SEL_offset                      6
#define         AC_BANK_MTX_IO36_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO35_SEL_offset                      0
#define         AC_BANK_MTX_IO35_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR8                  0x1a8
#define         AC_BANK_MTX_IO44_SEL_offset                      24
#define         AC_BANK_MTX_IO44_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO43_SEL_offset                      18
#define         AC_BANK_MTX_IO43_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO42_SEL_offset                      12
#define         AC_BANK_MTX_IO42_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO41_SEL_offset                      6
#define         AC_BANK_MTX_IO41_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO40_SEL_offset                      0
#define         AC_BANK_MTX_IO40_SEL_mask                        0x0000003f
#define     AC_BANK_MTX_CR9                  0x1ac
#define         AC_BANK_MTX_IO49_SEL_offset                      24
#define         AC_BANK_MTX_IO49_SEL_mask                        0x3f000000
#define         AC_BANK_MTX_IO48_SEL_offset                      18
#define         AC_BANK_MTX_IO48_SEL_mask                        0x00fc0000
#define         AC_BANK_MTX_IO47_SEL_offset                      12
#define         AC_BANK_MTX_IO47_SEL_mask                        0x0003f000
#define         AC_BANK_MTX_IO46_SEL_offset                      6
#define         AC_BANK_MTX_IO46_SEL_mask                        0x00000fc0
#define         AC_BANK_MTX_IO45_SEL_offset                      0
#define         AC_BANK_MTX_IO45_SEL_mask                        0x0000003f
#define     DDRGPLL_FRQ_CHK_CTL              0x1b0
#define         DDRGPLL_DET_DIS_offset                           0
#define         DDRGPLL_DET_DIS_mask                             0x00000001
#define     DDRGPLL_TGT_HTHD                 0x1b4
#define         DDRGPLL_TGTCLK_CNT_HTHD_offset                   0
#define         DDRGPLL_TGTCLK_CNT_HTHD_mask                     0xffffffff
#define     DDRGPLL_TGT_LTHD                 0x1b8
#define         DDRGPLL_TGTCLK_CNT_LTHD_offset                   0
#define         DDRGPLL_TGTCLK_CNT_LTHD_mask                     0xffffffff
#define     DDRGPLL_REF_THD                  0x1bc
#define         DDRGPLL_REFCLK_CNT_THD_offset                    0
#define         DDRGPLL_REFCLK_CNT_THD_mask                      0x0000ffff
#define     DDRGPLL_ERR_DET                  0x1c0
#define         DDRGPLL_ERR_CLKDET_offset                        0
#define         DDRGPLL_ERR_CLKDET_mask                          0x00000001
