/*
This file will be generated by FD
*/

#ifndef __AL_PARAMS__
#define __AL_PARAMS__

#ifdef __cplusplus
extern "C" {
#endif

#include "platform_init.h"

/*----------------------------------------------------------------------------
* Define Interrupt Number
*----------------------------------------------------------------------------*/
typedef enum {
    SOC_DMACAHB_IRQn     =  78,
    GPIO0_IRQn           =  84,
    SOC_MMC0_IRQn        =  94,
    SOC_MMC1_IRQn        =  95,
    SOC_IIC0_IRQn        =  96,
    SOC_IIC1_IRQn        =  97,
    SOC_INT130_IRQn      =  143,
    SOC_UART0_IRQn       =  102,
    SOC_UART1_IRQn       =  103,
    SOC_CAN0_IRQn        =  104,
    SOC_CAN1_IRQn        =  105,
    SOC_INT_MAX          =  256,
    NPU_HARD_IRQn        =  144,
    NPU_SOFT_IRQn        =  129,
} AL_IrqNumEnum;


/*----------------------------------------------------------------------------
  Define System clocks
 *----------------------------------------------------------------------------*/
#define SYSTEM_CLOCK            (50000000UL)

/*----------------------------------------------------------------------------
  Define System base addr
 *----------------------------------------------------------------------------*/
#define SYSTIMER__BASE_ADDR     (0x68020000UL)
#define CRP__BASE_ADDR          (0xF8801000UL)

/*----------------------------------------------------------------------------
  Define Uart params
 *----------------------------------------------------------------------------*/
#define HAVE_UARTPS_DRIVER

#define AL_UART_NUM_INSTANCE    (2)

#define UART0__BASE_ADDR        (0xF8400000UL)
#define UART1__BASE_ADDR        (0xF8401000UL)

#define UART_CLOCK              (40000000UL)

/*----------------------------------------------------------------------------
  Define SPI params
 *----------------------------------------------------------------------------*/
#define HAVE_SPIPS_DRIVER       (2)

/*----------------------------------------------------------------------------
  Define CAN params
 *----------------------------------------------------------------------------*/
#define HAVE_CANPS_DRIVER

#define AL_CAN_NUM_INSTANCE     (2)

#define CAN0__BASE_ADDR         (0xF8408000UL)
#define CAN1__BASE_ADDR         (0xF8409000UL)

#define CAN_CLOCK               (80000000UL)

#define CAN_TOP_CFG_CTRL_ADDR   (0xF8800164UL)

/*----------------------------------------------------------------------------
  Define DMACAHB params
 *----------------------------------------------------------------------------*/
#define HAVE_DMACAHBPS_DRIVER

#define AL_DMACAHB_NUM_INSTANCE (2)

#define DMACAHB__BASE_ADDR      (0xF804D000UL)

#define DMACAHB_CH_NUM          (8)

/* 0xF841F800 - 0xF841F80C */
#define DMACAHB_LOCK_ADDR       (0xF841F80CUL)
#define DMACAHB_CH_STATE_ADDR   (0xF88001B0UL)

/*----------------------------------------------------------------------------
  Define MMC params
 *----------------------------------------------------------------------------*/
#define HAVE_MMCPS_DRIVER

#define AL_MMC_NUM_INSTANCE     (2)

#define MMC0__BASE_ADDR         (0xF8049000UL)
#define MMC1__BASE_ADDR         (0xF804A000UL)

#define MMC0_TOP_CFG_CTRL_ADDR  (0xF8800150UL)
#define MMC1_TOP_CFG_CTRL_ADDR  (0xF8800154UL)

#define MMC0_BUS_WIDTH          (8)
#define MMC1_BUS_WIDTH          (4)

#define MMC0_CLK_IN_KHZ         (10000UL)
#define MMC1_CLK_IN_KHZ         (10000UL)

/*----------------------------------------------------------------------------
  Define IIC params
 *----------------------------------------------------------------------------*/
#define HAVE_IICPS_DRIVER

#define AL_IIC_NUM_INSTANCE     (2)

#define I2C0__BASE_ADDR         0xF8414000ULL
#define I2C1__BASE_ADDR         0xF8415000ULL

#define I2C_CLOCK               (40000000UL)

#ifdef __cplusplus
}
#endif

#endif  /* __AL_PARAMS__ */
