# (0) include config file

# (1.1) add submodule resource file
SRC_DIR = ./src \
          ./src/ddr_demo

# (1.2) add submodule include
INC_DIR += ./inc \
           ./inc/ddr_demo \
           ./inc/ddr_demo/ddr_regs

# (3) set specificity FLAGS
LIBNAME := plat


include $(AL_SDK_ROOT)/tools/make/rules.mk
