#ifndef NPU_DEFINES_H
#define NPU_DEFINES_H

#include "driver_api.h"

// #define PRINT_NPU_CMD // if defined, npu cmd generated by npu_driver will be printed
#define HW_PREPROCESS // if defined, decode JPG && YUV2RGB are done on HW

#define RUN_BARE_METAL 0
#define RUN_LINUX 1

#define WEIGHT_DATA_LENGTH (70 * 1024 * 1024) // 70M

#define FM_SIZE_MASK 0x7fff
#define FM_MIN_SIZE 0x8000
#define FM_MIN_SIZE_BIT_WIDTH 15
#define BUDDY_LEVEL 10

#define MEM_ALLOC_BUDDY
// #define MEM_ALLOC_LINEAR

// #define RUN_PLATFORM_LINUX
#define RUN_PLATFORM_BM


typedef union
{
    uint8_t  u8  [8] ;
    uint16_t u16 [4] ;
    uint32_t u32 [2] ;
    uint64_t u64 ;
    int8_t  i8  [8] ;
    int16_t i16 [4] ;
    int32_t i32 [2] ;
    int64_t i64 ;
    void*   pointer ;
} any_data_t;


#endif