TARGET = hard_test

NUCLEI_SDK_ROOT = ../..

SRCDIRS = . src

INCDIRS = . inc

#COMMON_FLAGS := -O2

SOC := demoapu

COMPILE_PREFIX := /opt/toolchain/gcc-arm-11.2-2022.02-x86_64-aarch64-none-elf/bin/aarch64-none-elf-

PROGRAM := ./

V := 1

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
