/*
 * Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***************************** Include Files *********************************/
#include "al_xadc_dev.h"

/************************** Variable Definitions *****************************/
/* Hardware config generated by TD */
extern AL_XADC_HwConfigStruct AlXadc_HwConfig[AL_XADC_NUM_INSTANCE];
/**
 * This function look up hardware config structure.
 * @param   DeviceId is hardware module id
 * @return
 *          - AL_XADC_HwConfigStruct for hardware config
 * @note
*/
AL_XADC_HwConfigStruct *AlXadc_Dev_LookupConfig(AL_U32 DevId)
{
    AL_U32 Index;
    AL_XADC_HwConfigStruct *ConfigPtr = AL_NULL;

    for (Index = 0; Index < AL_XADC_NUM_INSTANCE; Index++) {
        if (AlXadc_HwConfig[Index].DeviceId == DevId) {
            ConfigPtr = &AlXadc_HwConfig[Index];
            break;
        }
    }
    return ConfigPtr;
}

/************************** Constant Definitions *****************************/

static AL_XADC_InitStruct XadcDefInitConfigs = {

    .InputSingal             = AL_XADC_SINGLE_ENDED,
    .Resolution              = AL_XADC_12BIT_MODE,
    .RefVoltag               = AL_XADC_REF_INTER_REF,
    .ClkSource               = AL_XADC_CLK_PL_70MHz,
    .ConvMode                = AL_XADC_CONTINUE_MODE,
    .ExternalMux             = AL_XADC_NORMAL_MODE,
    .MaxConvChannelNum       = 7
};

/************************** Function Prototypes ******************************/

/************************** Function Definitions ******************************/

AL_S32 AlXadc_Dev_Init(AL_XADC_DevStruct *Xadc, AL_U32 DevId, AL_XADC_InitStruct *InitConfig)
{
    AL_XADC_HwConfigStruct *XadcHwConfig;
    AL_ASSERT((Xadc != AL_NULL && DevId < AL_XADC_NUM_INSTANCE), AL_XADC_ERR_ILLEGAL_PARAM);

    XadcHwConfig          = AlXadc_Dev_LookupConfig(DevId);
    Xadc->DevId           = DevId;
    Xadc->XadcBaseAddr    = XadcHwConfig->XadcBaseAddress;
    Xadc->GpBaseAddr      = XadcHwConfig->GpBaseAddress;
    Xadc->IntrNum         = XadcHwConfig->IntrNum;
    Xadc->Configs         = (InitConfig == AL_NULL) ? XadcDefInitConfigs : (*InitConfig);

    AlXadc_ll_XadcIntr(Xadc->XadcBaseAddr, AL_TRUE);
    AlXadc_ll_MaskXadcIntr(Xadc->XadcBaseAddr, AL_FALSE);

    /*Turn off write protection*/
    AlXadc_ll_GpCloseWriteProtection();

    AlXadc_ll_GpSwReset(Xadc->GpBaseAddr);
    AlXadc_ll_GpSetInputSingal(Xadc->GpBaseAddr, Xadc->Configs.InputSingal);
    AlXadc_ll_GpSetResolution(Xadc->GpBaseAddr, Xadc->Configs.Resolution);
    AlXadc_ll_GpSetRefVoltag(Xadc->GpBaseAddr, Xadc->Configs.RefVoltag);
    AlXadc_ll_GpEnableAnalogMux(Xadc->GpBaseAddr, AL_XADC_ALLOW);
    AlXadc_ll_GpEnablePhyExternalMux(Xadc->GpBaseAddr, Xadc->Configs.ExternalMux);
    AlXadc_ll_GpSetAdcClkSource(Xadc->GpBaseAddr,Xadc->Configs.ClkSource);
    AlXadc_ll_GpSetConvMode(Xadc->GpBaseAddr, Xadc->Configs.ConvMode);
    AlXadc_ll_GpSetMaxConvChannelNum(Xadc->GpBaseAddr, Xadc->Configs.MaxConvChannelNum);

    AlXadc_ll_GpClrAllChannelIntr(Xadc->GpBaseAddr);
    AlXadc_ll_GpMaskAllChannelIntr(Xadc->GpBaseAddr);

    return AL_OK;
}

AL_S32 AlXadc_Dev_SetIomuxForChannel(AL_XADC_DevStruct *Xadc, AL_XADC_ChannelCfg *ChannelCfg)
{
    AL_ASSERT(((Xadc != AL_NULL) && (ChannelCfg != AL_NULL)), AL_XADC_ERR_ILLEGAL_PARAM);

    switch (ChannelCfg->ChannelNum)
    {
    case AL_XADC_CHANNEL0:
        AlXadc_ll_GpSetIomuxForChannel0(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL1:
        AlXadc_ll_GpSetIomuxForChannel1(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL2:
        AlXadc_ll_GpSetIomuxForChannel2(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL3:
        AlXadc_ll_GpSetIomuxForChannel3(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL4:
        AlXadc_ll_GpSetIomuxForChannel4(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL5:
        AlXadc_ll_GpSetIomuxForChannel5(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL6:
        AlXadc_ll_GpSetIomuxForChannel6(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    case AL_XADC_CHANNEL7:
        AlXadc_ll_GpSetIomuxForChannel7(Xadc->GpBaseAddr, ChannelCfg->ChannelIomux);
        break;
    default:
        return AL_XADC_ERR_NOT_SUPPORT;
        break;
    }
    return AL_OK;
}

AL_S32 AlXadc_Dev_SetChannelThresHold(AL_XADC_DevStruct *Xadc, AL_XADC_ChannelCfg *ChannelCfg)
{
    AL_ASSERT(((Xadc != AL_NULL) && (ChannelCfg != AL_NULL)), AL_XADC_ERR_ILLEGAL_PARAM);

    AlXadc_ll_GpSetXadcChxLth(Xadc->GpBaseAddr, ChannelCfg->ChannelNum, ChannelCfg->LthValue);
    AlXadc_ll_GpSetXadcChxGth(Xadc->GpBaseAddr, ChannelCfg->ChannelNum, ChannelCfg->GthValue);

    return AL_OK;
}

AL_S32 AlXadc_Dev_ClrIntr(AL_XADC_DevStruct *Xadc, AL_XADC_IntrtypeEnum IntrType)
{
    AlXadc_ll_GpClrIntr(Xadc->GpBaseAddr, IntrType);

    return AL_OK;
}

AL_S32 AlXadc_Dev_EnableIntr(AL_XADC_DevStruct *Xadc, AL_XADC_IntrtypeEnum IntrType, AL_BOOL State)
{
    AlXadc_ll_GpMaskIntr(Xadc->GpBaseAddr, IntrType, ~State);

    return AL_OK;
}

AL_S32 AlXadc_Dev_EnableXadc(AL_XADC_DevStruct *Xadc)
{
    AL_ASSERT((Xadc != AL_NULL), AL_XADC_ERR_ILLEGAL_PARAM);

    AlXadc_ll_GpEnableAdc(Xadc->GpBaseAddr);
}

AL_S32 AlXadc_Dev_DisableXadc(AL_XADC_DevStruct *Xadc)
{
    AL_ASSERT((Xadc != AL_NULL), AL_XADC_ERR_ILLEGAL_PARAM);

    AlXadc_ll_GpDisableAdc(Xadc->GpBaseAddr);
}

AL_VOID AlXadc_Dev_StartConv(AL_XADC_DevStruct *Xadc)
{
    AL_ASSERT((Xadc != AL_NULL), AL_XADC_ERR_ILLEGAL_PARAM);

    AlXadc_ll_GpTriggerConv(Xadc->GpBaseAddr, AL_XADC_START_CONV);
}

AL_VOID AlXadc_Dev_StopConv(AL_XADC_DevStruct *Xadc)
{
    AL_ASSERT((Xadc != AL_NULL), AL_XADC_ERR_ILLEGAL_PARAM);

    AlXadc_ll_GpTriggerConv(Xadc->GpBaseAddr, AL_XADC_END_CONV);
}

AL_U16 AlXadc_Dev_GetAdcData(AL_XADC_DevStruct *Xadc, AL_XADC_ChannelEnum ChannelNum)
{
    while (1) {
        if(AlXadc_ll_GpGetXadcFlag(Xadc->GpBaseAddr) & (1 << AL_XADC_FLAG_DONE)) {
            Xadc->XadcData->ChannelNum = ChannelNum;
            Xadc->XadcData->ChannelData =AlXadc_ll_GpGetXadcData(Xadc->GpBaseAddr, ChannelNum);
            break;
        }
    }
    return Xadc->XadcData->ChannelData;
}


AL_VOID AlXadc_Dev_IntrDoneHandler(AL_XADC_DevStruct *Xadc)
{
    AL_U32 Index;
    AL_XADC_EventStruct XadcEvent = {0};

    AL_U16 XadcFlag = AlXadc_ll_GpGetXadcFlag(Xadc->GpBaseAddr);
    for (Index = 0; Index <= Xadc->Configs.MaxConvChannelNum; Index++) {
        if (XadcFlag & (1 << (Index + AL_XADC_FLAG_COMP_VC0))) {
            Xadc->XadcData[Index].ChannelNum = Index;
            Xadc->XadcData[Index].ChannelData = AlXadc_ll_GpGetXadcData(Xadc->GpBaseAddr, Index);
            XadcEvent.EventData |= BIT(Index);
        }
    }

    XadcEvent.Events = AL_XADC_EVENT_GETDATA_DONE;
    if (Xadc->EventCallBack) {
        (*Xadc->EventCallBack)(XadcEvent, Xadc->EventCallBackRef);
    }

    AlXadc_ll_GpClrIntr(Xadc->GpBaseAddr, AL_XADC_INTR_DONE);
}

AL_VOID AlXadc_Dev_IntrGthHandler(AL_XADC_DevStruct *Xadc)
{
    AL_U32 Index;
    AL_XADC_EventStruct XadcEvent = {0};

    AL_U16 XadcFlag = AlXadc_ll_GpGetXadcFlag(Xadc->GpBaseAddr);
    for (Index = 0; Index <= Xadc->Configs.MaxConvChannelNum; Index++) {
        if (XadcFlag & (1 << (Index + AL_XADC_FLAG_COMP_VC0))) {
            Xadc->XadcData[Index].ChannelNum = Index;
            Xadc->XadcData[Index].ChannelData = AlXadc_ll_GpGetXadcData(Xadc->GpBaseAddr, Index);
            XadcEvent.EventData |= BIT(Index);
        }
    }

    XadcEvent.Events = AL_XADC_EVENT_GETDATA_GTH;
    if (Xadc->EventCallBack) {
        (*Xadc->EventCallBack)(XadcEvent, Xadc->EventCallBackRef);
    }

    AlXadc_ll_GpClrIntr(Xadc->GpBaseAddr, AL_XADC_INTR_GTH);
}

AL_VOID AlXadc_Dev_IntrLthHandler(AL_XADC_DevStruct *Xadc)
{
    AL_U32 Index;
    AL_XADC_EventStruct XadcEvent = {0};

    AL_U16 XadcFlag = AlXadc_ll_GpGetXadcFlag(Xadc->GpBaseAddr);
    for (Index = 0; Index <= Xadc->Configs.MaxConvChannelNum; Index++) {
        if (XadcFlag & (1 << (Index + AL_XADC_FLAG_COMP_VC0))) {
            Xadc->XadcData[Index].ChannelNum = Index;
            Xadc->XadcData[Index].ChannelData = AlXadc_ll_GpGetXadcData(Xadc->GpBaseAddr, Index);
            XadcEvent.EventData |= BIT(Index);
        }
    }

    XadcEvent.Events = AL_XADC_EVENT_GETDATA_LTH;
    if (Xadc->EventCallBack) {
        (*Xadc->EventCallBack)(XadcEvent, Xadc->EventCallBackRef);
    }
    AlXadc_ll_GpClrIntr(Xadc->GpBaseAddr, AL_XADC_INTR_LTH);
}

AL_VOID AlXadc_Dev_IntrErrorHandler(AL_XADC_DevStruct *Xadc)
{
    AL_U32 Index;
    AL_XADC_EventStruct XadcEvent = {0};

    AL_U16 XadcFlag = AlXadc_ll_GpGetXadcFlag(Xadc->GpBaseAddr);
    for (Index = 0; Index <= Xadc->Configs.MaxConvChannelNum; Index++) {
        if (XadcFlag & (1 << (Index + AL_XADC_FLAG_COMP_VC0))) {
            XadcEvent.EventData |= BIT(Index);
        }
    }

    XadcEvent.Events = AL_XADC_EVENT_ERROR;
    if (Xadc->EventCallBack) {
        (*Xadc->EventCallBack)(XadcEvent, Xadc->EventCallBackRef);
    }
    AlXadc_ll_GpClrIntr(Xadc->GpBaseAddr, AL_XADC_INTR_ERROR);
}


#define AL_XADC_IS_INTR_DONE(Status)            (Status & (1 << (AL_XADC_INTR_DONE)))
#define AL_XADC_IS_INTR_GTH(Status)             (Status & (1 << (AL_XADC_INTR_GTH)))
#define AL_XADC_IS_INTR_LTH(Status)             (Status & (1 << (AL_XADC_INTR_LTH)))
#define AL_XADC_IS_INTR_ERROR(Status)           (Status & (1 << (AL_XADC_INTR_ERROR)))

AL_VOID AlXadc_Dev_IntrHandler(AL_VOID *Instance)
{
    AL_XADC_DevStruct *Xadc = (AL_XADC_DevStruct *)Instance;
    AL_U16 IntrStatus = AlXadc_ll_GpGetIntrType(Xadc->GpBaseAddr);
    if (AL_XADC_IS_INTR_DONE(IntrStatus)) {
        AlXadc_Dev_IntrDoneHandler(Xadc);
    }
    if (AL_XADC_IS_INTR_GTH(IntrStatus)) {
        AlXadc_Dev_IntrGthHandler(Xadc);
    }
    if (AL_XADC_IS_INTR_LTH(IntrStatus)) {
        AlXadc_Dev_IntrLthHandler(Xadc);
    }
    if (AL_XADC_IS_INTR_ERROR(IntrStatus)) {
        AlXadc_Dev_IntrErrorHandler(Xadc);
    }
}

AL_S32 AlXadc_Dev_IoCtl(AL_XADC_DevStruct *Xadc, AL_XADC_IoCtlCmdEnum Cmd, AL_XADC_IoctlParamUnion *IoctlParam)
{
    AL_S32 Ret = AL_OK;

    AL_ASSERT((Xadc != AL_NULL), AL_XADC_ERR_ILLEGAL_PARAM);

    switch (Cmd)
    {
    case AL_XADC_IOCTL_SET_INPUTSINGAL: {
        AL_U8 InuputSignal = IoctlParam->InputSingal;
        AlXadc_ll_GpSetInputSingal(Xadc->GpBaseAddr, InuputSignal);
        break;
    }
    case AL_XADC_IOCTL_SET_RESOLUTION: {
        AL_U8 Resolution = IoctlParam->Resolution;
        AlXadc_ll_GpSetResolution(Xadc->GpBaseAddr, Resolution);
        break;
    }
    case AL_XADC_IOCTL_SET_REFVOLTAG: {
        AL_U8 RefVoltag = IoctlParam->RefVoltag;
        AlXadc_ll_GpSetRefVoltag(Xadc->GpBaseAddr, RefVoltag);
        break;
    }
    case AL_XADC_IOCTL_SET_CLKSOURCE: {
        AL_U8 ClkSource = IoctlParam->ClkSource;
        AlXadc_ll_GpSetAdcClkSource(Xadc->GpBaseAddr, ClkSource);
        break;
    }
    case AL_XADC_IOCTL_SET_CONVMODE: {
        AL_U8 ConvMode = IoctlParam->ConvMode;
        AlXadc_ll_GpSetConvMode(Xadc->GpBaseAddr, ConvMode);
        break;
    }
    case AL_XADC_IOCTL_SET_MAXCONVCHANNELNUM: {
        AL_U8 MaxConvChannelNum = IoctlParam->MaxConvChannelNum;
        AlXadc_ll_GpSetConvMode(Xadc->GpBaseAddr, MaxConvChannelNum);
        break;
    }
    default:
        break;
    }

    return Ret;
}

AL_S32 AlXadc_Dev_RegisterEventCallBack(AL_XADC_DevStruct *Xadc, AL_XADC_EventCallBack Callback, AL_VOID *CallbackRef)
{
    AL_ASSERT(((Xadc != AL_NULL) && (Callback != AL_NULL)), AL_XADC_ERR_ILLEGAL_PARAM);

    Xadc->EventCallBack        = Callback;
    Xadc->EventCallBackRef     = CallbackRef;

    return AL_OK;
}

AL_S32 AlXadc_Dev_UnRegisterEventCallBack(AL_XADC_DevStruct *Xadc)
{
    AL_ASSERT((Xadc != AL_NULL), AL_XADC_ERR_ILLEGAL_PARAM);

    Xadc->EventCallBack = (AL_XADC_EventCallBack)AL_NULL;

    return AL_OK;
}
