/*
 * This file will be generated by FD
*/

#ifndef __AL_PARAMS__
#define __AL_PARAMS__

#ifdef __cplusplus
extern "C" {
#endif

/*----------------------------------------------------------------------------
* Define Interrupt Number
*----------------------------------------------------------------------------*/
typedef enum {
    SysTimer_IRQn        =  7,
    GPIO0_IRQn           =  71,
    SOC_INT130_IRQn      =  130,
    SOC_UART0_IRQn       =  89,
    SOC_UART1_IRQn       =  90,
    SOC_CAN0_IRQn        =  91,
    SOC_CAN1_IRQn        =  92,
    SOC_INT_MAX          =  256,
    NPU_HARD_IRQn        =  131,
    NPU_SOFT_IRQn        =  116,
} AL_IrqNumEnum;

/*----------------------------------------------------------------------------
  Define System clocks
 *----------------------------------------------------------------------------*/
#define SYSTEM_CLOCK            (50000000UL)

/*----------------------------------------------------------------------------
  Define System base addr
 *----------------------------------------------------------------------------*/
#define SYSTIMER__BASE_ADDR     (0x68020000UL)
#define ECLIC__BASE_ADDR        (0x68000000UL)
#define CRP__BASE_ADDR          (0xF8801000UL)

/*----------------------------------------------------------------------------
  Define Uart params
 *----------------------------------------------------------------------------*/
#define HAVE_UARTPS_DRIVER

#define AL_UART_NUM_INSTANCE    (2)

#define UART0__BASE_ADDR        (0xF8400000UL)
#define UART1__BASE_ADDR        (0xF8401000UL)

#define UART_CLOCK              (40000000UL)

/*----------------------------------------------------------------------------
  Define SPI params
 *----------------------------------------------------------------------------*/
#define HAVE_SPIPS_DRIVER


/*----------------------------------------------------------------------------
  Define CAN params
 *----------------------------------------------------------------------------*/
#define HAVE_CANPS_DRIVER


/*----------------------------------------------------------------------------
  Define QSPI params
 *----------------------------------------------------------------------------*/
#define HAVE_QSPIPS_DRIVER


/*----------------------------------------------------------------------------
  Define I2C params
 *----------------------------------------------------------------------------*/
#define HAVE_I2CPS_DRIVER


#ifdef __cplusplus
}
#endif

#endif  /* __AL_PARAMS__ */
