/*
 * This file will be generated by FD
*/

#ifndef __AL_PARAMS__
#define __AL_PARAMS__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    GPIO0_IRQn           =  84,
    SOC_INT130_IRQn      =  (130 + 13),
    SOC_INT89_IRQn       =  (89  + 13),
    SOC_INT_MAX          =  256,
};

/*----------------------------------------------------------------------------
  Define clocks
 *----------------------------------------------------------------------------*/
#ifndef SYSTEM_CLOCK
#define SYSTEM_CLOCK    (50000000UL)
#endif

#ifdef __cplusplus
}
#endif

#endif  /* __AL_PARAMS__ */
