# (0) include config file

# (1.1) add submodule resource file
SRC_DIR = ./src

# (1.2) add submodule include
INC_DIR += ./inc

# (3) set specificity FLAGS
LIBNAME := hpf


include ../../../tools/make/rules.mk
