TARGET = spg_lock_test

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = .

INCDIRS = .

COMMON_FLAGS := -DCONFIG_PRINTK

#COMMON_FLAGS := -DSWITCH_TO_EL0_FROM_EL3

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
