TARGET = xmon_intr_state

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = . src ./../../demo_dmac_axi/dmac_axi_driver ../xmon_drivers

INCDIRS = . inc ./../../demo_dmac_axi/dmac_axi_driver ../xmon_drivers

#COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
