TARGET = alsecure_test

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .

INCDIRS = .

COMMON_FLAGS := -O2 -Wall
#-Werror=uninitialized

#SOC := demoapu

#COMPILE_PREFIX := /opt/toolchain/gcc-arm-11.2-2022.02-x86_64-aarch64-none-elf/bin/aarch64-none-elf-

#PROGRAM := ./

#V := 1

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
