/*****************************************************************************/
/**
 * @file al_csu_reg.h
 * This is the header file which contains definitions for the CSU system
 * registers.
 *
 * <pre>
 * MODIFICATION HISTORY:
 *
 * Ver   Who  Date        Changes
 * ----- ---- -------- -------------------------------------------------------
 * 1.00  c.z  3/10/22  Initial release
 * </pre>
 *
 * @note
 * Upte to date with spg_extract_file release version 31 on 5/27/2022.
 ******************************************************************************/

#ifndef AL_CSU_REG_H
#define AL_CSU_REG_H

#include "al9000_csu_map.h"
#include "al9000_registers.h"
// #include "al_csu_config.h"

/* NVI BASE address */
#define CSU_QSPI_CTRL_L QSPI_CTRL_L
#define CSU_QSPI_CTRL_H QSPI_CTRL_H
#define CSU_SDIO0_L SDIO0_L
#define CSU_SDIO0_H SDIO0_H
#define CSU_SDIO1_L SDIO1_L
#define CSU_SDIO1_H SDIO1_H
#define CSU_NANDC_CFG_L NANDC_CFG_L
#define CSU_NANDC_CFG_H NANDC_CFG_H

/* CSU lifetime register: TOS_S, RWL0_RESERVED */
#define CSU_LIFETIME_REG_ADDR TOP_S__RWL0_RESERVED__ADDR

/* CSU footprint register: TOS_S, RWL1_RESERVED ~  RWL4_RESERVED */
#define CSU_FOOTPRINT0_REG_ADDR TOP_S__RWL1_RESERVED__ADDR
#define CSU_FOOTPRINT1_REG_ADDR TOP_S__RWL2_RESERVED__ADDR
#define CSU_FOOTPRINT2_REG_ADDR TOP_S__RWL3_RESERVED__ADDR
#define CSU_FOOTPRINT3_REG_ADDR TOP_S__RWL4_RESERVED__ADDR

/* CSU local registers */

#define CSU_IDCODE_ADDR CSU_LOCAL__CSU_IDCODE__ADDR
#define CSU_VERSION_ADDR CSU_LOCAL__CSU_VERSION__ADDR
#define CSU_TAMPER_TRIG_ADDR CSU_LOCAL__CSU_TAMPER_TRIG__ADDR
#define TRNG_ENABLE_ADDR CSU_LOCAL__TRNG_ENABLE__ADDR
#define CSU_RESET_VECTOR_ADDR CSU_LOCAL__CSU_RESET_VECTOR__ADDR
#define NON_SECURE_LOCKDOWN_ADDR CSU_LOCAL__NON_SECURE_LOCKDOWN__ADDR
#define SECURE_LOCKDOWN_ADDR CSU_LOCAL__SECURE_LOCKDOWN__ADDR
#define CSU_ROM_DIGEST_0_ADDR CSU_LOCAL__CSU_ROM_DIGEST_0__ADDR
#define CSU_ROM_DIGEST_1_ADDR CSU_LOCAL__CSU_ROM_DIGEST_1__ADDR
#define CSU_ROM_DIGEST_2_ADDR CSU_LOCAL__CSU_ROM_DIGEST_2__ADDR
#define CSU_ROM_DIGEST_3_ADDR CSU_LOCAL__CSU_ROM_DIGEST_3__ADDR
#define CSU_ROM_DIGEST_4_ADDR CSU_LOCAL__CSU_ROM_DIGEST_4__ADDR
#define CSU_ROM_DIGEST_5_ADDR CSU_LOCAL__CSU_ROM_DIGEST_5__ADDR
#define CSU_ROM_DIGEST_6_ADDR CSU_LOCAL__CSU_ROM_DIGEST_6__ADDR
#define CSU_ROM_DIGEST_7_ADDR CSU_LOCAL__CSU_ROM_DIGEST_7__ADDR
#define CSU_EFUSE_DATA_0_ADDR CSU_LOCAL__CSU_EFUSE_DATA_0__ADDR
#define CSU_EFUSE_DATA_1_ADDR CSU_LOCAL__CSU_EFUSE_DATA_1__ADDR
#define CSU_EFUSE_DATA_2_ADDR CSU_LOCAL__CSU_EFUSE_DATA_2__ADDR
#define CSU_EFUSE_DATA_3_ADDR CSU_LOCAL__CSU_EFUSE_DATA_3__ADDR
#define CSU_EFUSE_DATA_4_ADDR CSU_LOCAL__CSU_EFUSE_DATA_4__ADDR
#define CSU_EFUSE_DATA_5_ADDR CSU_LOCAL__CSU_EFUSE_DATA_5__ADDR
#define CSU_EFUSE_DATA_6_ADDR CSU_LOCAL__CSU_EFUSE_DATA_6__ADDR
#define CSU_EFUSE_DATA_7_ADDR CSU_LOCAL__CSU_EFUSE_DATA_7__ADDR
#define CSU_EFUSE_DATA_8_ADDR CSU_LOCAL__CSU_EFUSE_DATA_8__ADDR
#define CSU_EFUSE_DATA_9_ADDR CSU_LOCAL__CSU_EFUSE_DATA_9__ADDR
#define CSU_EFUSE_DATA_10_ADDR CSU_LOCAL__CSU_EFUSE_DATA_10__ADDR
#define CSU_EFUSE_DATA_11_ADDR CSU_LOCAL__CSU_EFUSE_DATA_11__ADDR
#define CSU_EFUSE_DATA_12_ADDR CSU_LOCAL__CSU_EFUSE_DATA_12__ADDR
#define CSU_EFUSE_DATA_13_ADDR CSU_LOCAL__CSU_EFUSE_DATA_13__ADDR
#define CSU_EFUSE_DATA_14_ADDR CSU_LOCAL__CSU_EFUSE_DATA_14__ADDR
#define CSU_EFUSE_DATA_15_ADDR CSU_LOCAL__CSU_EFUSE_DATA_15__ADDR
#define CSU_EFUSE_DATA_16_ADDR CSU_LOCAL__CSU_EFUSE_DATA_16__ADDR
#define CSU_EFUSE_DATA_17_ADDR CSU_LOCAL__CSU_EFUSE_DATA_17__ADDR
#define CSU_EFUSE_DATA_18_ADDR CSU_LOCAL__CSU_EFUSE_DATA_18__ADDR

typedef CSU_LOCAL__TRNG_ENABLE__ACC_T TrngEnableReg_t;
typedef CSU_LOCAL__NON_SECURE_LOCKDOWN__ACC_T NonSecureLockdownReg_t;
typedef CSU_LOCAL__SECURE_LOCKDOWN__ACC_T SecureLockdownReg_t;

/* TOP NS registers */

#define CSU_BOOT_MODE_ADDR TOP_NS__BOOT_MOD__ADDR
#define CFG_CTRL_OCM_ADDR TOP_NS__CFG_CTRL_OCM__ADDR

typedef TOP_NS__BOOT_MOD__ACC_T BootModeReg_t;

typedef union {
  u32 All;
  struct {
    u32 EccEn : 1;
    u32 DbgmSel : 3;
    u32 SbitIntrEn : 1;
    u32 DbitIntrEn : 1;
    u32 SbitIntrMsk : 1;
    u32 DbitIntrMsk : 1;
    u32 Reserved : 24;
  } Bit;
} CfgCtrlOcmReg_t;

/* TOP S registers */

#define ERR_HW_EN0_SET_ADDR TOP_S__ERR_HW_EN0_SET__ADDR
#define ERR_HW_EN0_CLR_ADDR TOP_S__ERR_HW_EN0_CLR__ADDR
#define ERR_HW_EN1_SET_ADDR TOP_S__ERR_HW_EN1_SET__ADDR
#define ERR_HW_EN1_CLR_ADDR TOP_S__ERR_HW_EN1_CLR__ADDR
#define INT_EN0_SET_ADDR TOP_S__INT_EN0_SET__ADDR
#define INT_EN0_CLR_ADDR TOP_S__INT_EN0_CLR__ADDR
#define INT_EN1_SET_ADDR TOP_S__INT_EN1_SET__ADDR
#define INT_EN1_CLR_ADDR TOP_S__INT_EN1_CLR__ADDR
#define INT_MSK0_SET_ADDR TOP_S__INT_MSK0_SET__ADDR
#define INT_MSK0_CLR_ADDR TOP_S__INT_MSK0_CLR__ADDR
#define INT_MSK1_SET_ADDR TOP_S__INT_MSK1_SET__ADDR
#define INT_MSK1_CLR_ADDR TOP_S__INT_MSK1_CLR__ADDR
#define INT_CLR0_ADDR TOP_S__INT_CLR0__ADDR
#define INT_CLR1_ADDR TOP_S__INT_CLR1__ADDR
#define INT_STATE0_ADDR TOP_S__INT_STATE0__ADDR
#define INT_STATE1_ADDR TOP_S__INT_STATE1__ADDR
#define RAW_HIS0_ADDR TOP_S__RAW_HIS0__ADDR
#define RAW_HIS1_ADDR TOP_S__RAW_HIS1__ADDR
#define SW_PMU_SHACK_ADDR TOP_S__SW_PMU_SHACK__ADDR
#define PMU_STAT_ADDR TOP_S__PMU_STAT__ADDR
#define JTAG_CTRL_ADDR TOP_S__JTAG_CTRL__ADDR
#define CSU_ERR_CODE_ADDR TOP_S__CSU_ERR_CODE__ADDR
#define MULTI_BOOT_ADDR TOP_S__MULTI_BOOT__ADDR
#define PWR_SP_THD_ADDR TOP_S__PWR_SP_THD__ADDR
#define PWR_LS_THD_ADDR TOP_S__PWR_LS_THD__ADDR
#define PWR_REPEAT_ADDR TOP_S__PWR_REPEAT__ADDR
#define APU_DBG_AUTH_ADDR TOP_S__APU_DBG_AUTH__ADDR
#define PL_PORT_AUTH_ADDR TOP_S__PL_PORT_AUTH__ADDR
#define EFUSE_SRST_ADDR TOP_S__EFUSE_SRST__ADDR
#define EFUSE_ECC_ADDR TOP_S__EFUSE_ECC__ADDR
#define EFUSE_GLB0_ADDR TOP_S__EFUSE_GLB0__ADDR
#define EFUSE_GLB1_ADDR TOP_S__EFUSE_GLB1__ADDR
#define EFUSE_GLB2_ADDR TOP_S__EFUSE_GLB2__ADDR
#define EFUSE_GLB3_ADDR TOP_S__EFUSE_GLB3__ADDR
#define EFUSE_GLB4_ADDR TOP_S__EFUSE_GLB4__ADDR
#define EFUSE_GLB5_ADDR TOP_S__EFUSE_GLB5__ADDR
#define EFUSE_GLB6_ADDR TOP_S__EFUSE_GLB6__ADDR
#define EFUSE_GLB7_ADDR TOP_S__EFUSE_GLB7__ADDR
#define EFUSE_GLB8_ADDR TOP_S__EFUSE_GLB8__ADDR
#define EFUSE_GLB9_ADDR TOP_S__EFUSE_GLB9__ADDR
#define EFUSE_GLB10_ADDR TOP_S__EFUSE_GLB10__ADDR
#define EFUSE_GLB11_ADDR TOP_S__EFUSE_GLB11__ADDR
#define EFUSE_GLB12_ADDR TOP_S__EFUSE_GLB12__ADDR
#define EFUSE_GLB13_ADDR TOP_S__EFUSE_GLB13__ADDR
#define EFUSE_GLB14_ADDR TOP_S__EFUSE_GLB14__ADDR
#define EFUSE_GLB15_ADDR TOP_S__EFUSE_GLB15__ADDR
#define EFUSE_GLB16_ADDR TOP_S__EFUSE_GLB16__ADDR
#define EFUSE_GLB17_ADDR TOP_S__EFUSE_GLB17__ADDR
#define EFUSE_GLB18_ADDR TOP_S__EFUSE_GLB18__ADDR
#define APU0_RESET_VECTOR_H_ADDR TOP_S__CFG_CTRL_APU0_RESET_VECTOR_H__ADDR
#define APU0_RESET_VECTOR_L_ADDR TOP_S__CFG_CTRL_APU0_RESET_VECTOR_L__ADDR
#define APU1_RESET_VECTOR_H_ADDR TOP_S__CFG_CTRL_APU1_RESET_VECTOR_H__ADDR
#define APU1_RESET_VECTOR_L_ADDR TOP_S__CFG_CTRL_APU1_RESET_VECTOR_L__ADDR
#define RPU_RESET_VECTOR_H_ADDR TOP_S__CFG_CTRL_RPU_RESET_VECTOR_H__ADDR
#define RPU_RESET_VECTOR_L_ADDR TOP_S__CFG_CTRL_RPU_RESET_VECTOR_L__ADDR
#define GLOBAL_SRST_N_ADDR TOP_S__GLOBAL_SRST_N__ADDR
#define XPU_SRST_ADDR TOP_S__XPU_SRST__ADDR

typedef TOP_S__ERR_HW_EN0_SET__ACC_T ErrHwEn0SetReg_t;
typedef TOP_S__ERR_HW_EN0_CLR__ACC_T ErrHwEn0ClrReg_t;
typedef TOP_S__ERR_HW_EN1_SET__ACC_T ErrHwEn1SetReg_t;
typedef TOP_S__ERR_HW_EN1_CLR__ACC_T ErrHwEn1ClrReg_t;
typedef TOP_S__INT_EN0_SET__ACC_T IntEn0SetReg_t;
typedef TOP_S__INT_EN0_CLR__ACC_T IntEn0ClrReg_t;
typedef TOP_S__INT_EN1_SET__ACC_T IntEn1SetReg_t;
typedef TOP_S__INT_EN1_CLR__ACC_T IntEn1ClrReg_t;
typedef TOP_S__INT_MSK0_SET__ACC_T IntMsk0SetReg_t;
typedef TOP_S__INT_MSK0_CLR__ACC_T IntMsk0ClrReg_t;
typedef TOP_S__INT_MSK1_SET__ACC_T IntMsk1SetReg_t;
typedef TOP_S__INT_MSK1_CLR__ACC_T IntMsk1ClrReg_t;
typedef TOP_S__INT_CLR0__ACC_T IntClr0Reg_t;
typedef TOP_S__INT_CLR1__ACC_T IntClr1Reg_t;
typedef TOP_S__INT_STATE0__ACC_T IntState0Reg_t;
typedef TOP_S__INT_STATE1__ACC_T IntState1Reg_t;
typedef TOP_S__RAW_HIS0__ACC_T RawHis0Reg_t;
typedef TOP_S__RAW_HIS1__ACC_T RawHis1Reg_t;
typedef TOP_S__SW_PMU_SHACK__ACC_T SwPmuShackReg_t;
typedef TOP_S__PMU_STAT__ACC_T PmuStatReg_t;
typedef TOP_S__JTAG_CTRL__ACC_T JtagCtrlReg_t;
typedef TOP_S__CSU_ERR_CODE__ACC_T CsuErrCodeReg_t;
typedef TOP_S__MULTI_BOOT__ACC_T MultiBootReg_t;
typedef TOP_S__PWR_SP_THD__ACC_T PwrSpThdReg_t;
typedef TOP_S__PWR_LS_THD__ACC_T PwrLsThdReg_t;
typedef TOP_S__PWR_REPEAT__ACC_T PwrRepeatReg_t;
typedef TOP_S__APU_DBG_AUTH__ACC_T ApuDbgAuthReg_t;
typedef TOP_S__PL_PORT_AUTH__ACC_T PlPortAuthReg_t;
typedef TOP_S__EFUSE_SRST__ACC_T EfuseSrstReg_t;
typedef TOP_S__EFUSE_ECC__ACC_T EfuseEccReg_t;
typedef TOP_S__EFUSE_GLB0__ACC_T EfuseGlb0Reg_t;
typedef TOP_S__EFUSE_GLB1__ACC_T EfuseGlb1Reg_t;
typedef TOP_S__EFUSE_GLB2__ACC_T EfuseGlb2Reg_t;
typedef TOP_S__EFUSE_GLB3__ACC_T EfuseGlb3Reg_t;
typedef TOP_S__EFUSE_GLB4__ACC_T EfuseGlb4Reg_t;
typedef TOP_S__EFUSE_GLB5__ACC_T EfuseGlb5Reg_t;
typedef TOP_S__EFUSE_GLB6__ACC_T EfuseGlb6Reg_t;
typedef TOP_S__EFUSE_GLB7__ACC_T EfuseGlb7Reg_t;
typedef TOP_S__EFUSE_GLB8__ACC_T EfuseGlb8Reg_t;
typedef TOP_S__EFUSE_GLB9__ACC_T EfuseGlb9Reg_t;
typedef TOP_S__EFUSE_GLB10__ACC_T EfuseGlb10Reg_t;
typedef TOP_S__EFUSE_GLB11__ACC_T EfuseGlb11Reg_t;
typedef TOP_S__EFUSE_GLB12__ACC_T EfuseGlb12Reg_t;
typedef TOP_S__EFUSE_GLB13__ACC_T EfuseGlb13Reg_t;
typedef TOP_S__EFUSE_GLB14__ACC_T EfuseGlb14Reg_t;
typedef TOP_S__EFUSE_GLB15__ACC_T EfuseGlb15Reg_t;
typedef TOP_S__EFUSE_GLB16__ACC_T EfuseGlb16Reg_t;
typedef TOP_S__EFUSE_GLB17__ACC_T EfuseGlb17Reg_t;
typedef TOP_S__EFUSE_GLB18__ACC_T EfuseGlb18Reg_t;
typedef TOP_S__CFG_CTRL_APU0_RESET_VECTOR_H__ACC_T Apu0ResetVectorHReg_t;
typedef TOP_S__CFG_CTRL_APU0_RESET_VECTOR_L__ACC_T Apu0ResetVectorLReg_t;
typedef TOP_S__CFG_CTRL_APU1_RESET_VECTOR_H__ACC_T Apu1ResetVectorHReg_t;
typedef TOP_S__CFG_CTRL_APU1_RESET_VECTOR_L__ACC_T Apu1ResetVectorLReg_t;
typedef TOP_S__CFG_CTRL_RPU_RESET_VECTOR_H__ACC_T RpuResetVectorHReg_t;
typedef TOP_S__CFG_CTRL_RPU_RESET_VECTOR_L__ACC_T RpuResetVectorLReg_t;
typedef TOP_S__GLOBAL_SRST_N__ACC_T GlobalSrstNReg_t;
typedef TOP_S__XPU_SRST__ACC_T XpuSrstReg_t;

/* CRP registers */

#define CLK_SEL_ADDR CRP__CLK_SEL__ADDR
#define ANA_PVT_ADDR CRP__ANA_PVT__ADDR
#define ANA_EFUSE_ADDR CRP__ANA_EFUSE__ADDR
#define JTAG_MODE_ADDR CRP__JTAG_MODE__ADDR
#define RST_REASON_ADDR CRP__RST_REASON__ADDR
#define WDT_OUT_CTRL_ADDR CRP__WDT_OUT_CTRL__ADDR

typedef CRP__CLK_SEL__ACC_T ClkSelReg_t;
typedef CRP__WDT_OUT_CTRL__ACC_T WdtOutCtrlReg_t;
typedef CRP__RST_REASON__ACC_T RstReasonReg_t;
typedef CRP__JTAG__ACC_T JtagReg_t;
typedef CRP__ANA_EFUSE__ACC_T AnaEfuseReg_t;
typedef CRP__ANA_PVT__ACC_T AnaPvtReg_t;

#define SRST_CTRL0_ADDR CRP__SRST_CTRL0__ADDR
#define SRST_CTRL1_ADDR CRP__SRST_CTRL1__ADDR
#define SRST_CTRL2_ADDR CRP__SRST_CTRL2__ADDR
#define SRST_CTRL3_ADDR CRP__SRST_CTRL3__ADDR

typedef CRP__SRST_CTRL0__ACC_T SrstCtrl0Reg_t;
typedef CRP__SRST_CTRL1__ACC_T SrstCtrl1Reg_t;
typedef CRP__SRST_CTRL2__ACC_T SrstCtrl2Reg_t;
typedef CRP__SRST_CTRL3__ACC_T SrstCtrl3Reg_t;

#endif /* AL_CSU_REG_H */
