/*
 * Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __AL_SOC_BOARD_INIT_H_
#define __AL_SOC_BOARD_INIT_H_

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _UL
#define _UL unsigned int
#endif

/* config opcode */
#define CONFIG_EXIT         0U
#define CONFIG_CLEAR        1U
#define CONFIG_WRITE        2U
#define CONFIG_MASKWRITE    3U
#define CONFIG_MASKPOLL     4U
#define CONFIG_MASKDELAY    5U
#define NEW_ALSOC_ERR_CODE  6U

#define CONFIG_POLL_TIME    100000

/* Encode number of arguments */
#define CONFIG_REG_EXIT()                    ( (CONFIG_EXIT      << 4 ) | 0 )
#define CONFIG_REG_CLEAR(addr)               ( (CONFIG_CLEAR     << 4 ) | 1 ) , addr
#define CONFIG_REG(addr,val)                 ( (CONFIG_WRITE     << 4 ) | 2 ) , addr, val
#define CONFIG_REG_MASK(addr,mask,val)       ( (CONFIG_MASKWRITE << 4 ) | 3 ) , addr, mask, val

/* Returns codes  of ALSOC_Init */
#define ALSOC_INIT_SUCCESS         (0)    // success
#define ALSOC_INIT_OPCODE_ERROR    (1)    // config opcode error
#define ALSOC_INIT_VERSION_ERROR   (2)    // data error
#define ALSOC_INIT_TIMEOUT         (3)    // timeout

/* Silicon Versions */
#define SOC_VERSION_1 0


/* This flag to be used by FSBL to check whether apu_post_config() proc exixts */
#define ALSOC_POST_CONFIG

/* Freq of all peripherals */
#define Hz                                        1
#define MHz                                 1000000
#define MHZ                                 1000000
#define KHZ                                 1000

#define ALSOC_APU_CLOCK         (100*MHZ)

#define UART_CLOCK                         ( 50*MHz)
#define CAN_CLOCK                          ( 80*MHz)
#define GBE_CLOCK                          ( 25*MHz)
#define ADC_CLOCK                           (50*MHz)

/**
 * clocks defined in FD
 */
/*----------------------------------------------------------------------------
  Define System clocks
 *----------------------------------------------------------------------------*/

#if defined __aarch64__
#ifdef AL_OSC_25
#define SYSTEM_CLOCK            (25*MHZ)
#elif defined AL_OSC_33
#define SYSTEM_CLOCK            (33333333UL)
#elif defined AL_OSC_50
#define SYSTEM_CLOCK            (50*MHZ)
#else
/* for emulation platform */
#define SYSTEM_CLOCK            (50*MHZ)
#endif
#else
#ifdef AL_CLK_CONFIG
#ifdef AL_OSC_25
#define SYSTEM_CLOCK            (200*MHZ)
#elif defined AL_OSC_33
#if (defined AL_CLK_800M || defined AL_CLK_400M || defined AL_CLK_1200M)
#define SYSTEM_CLOCK            (400*MHZ)
#elif defined AL_CLK_1000M
#define SYSTEM_CLOCK            (333333333UL)
#else
#error "undefined RPU CLK"
#endif
#elif defined AL_OSC_50
#define SYSTEM_CLOCK            (400*MHZ)
#else
#error "undefined OSC"
#endif
#else
#ifdef AL_OSC_25
#define SYSTEM_CLOCK            (200*MHZ)
#elif defined AL_OSC_33
#define SYSTEM_CLOCK            (266666666UL)
#elif defined AL_OSC_50
#define SYSTEM_CLOCK            (400*MHZ)
#else
/* for emulation platform */
#define SYSTEM_CLOCK            (50*MHZ)
#endif
#endif
#endif

#ifdef AL_CLK_CONFIG
#define UART_CLOCK              (50*MHZ)
#else
#ifdef AL_OSC_25
#define UART_CLOCK              (25*MHZ)
#elif defined AL_OSC_33
#define UART_CLOCK              (33333333UL)
#elif defined AL_OSC_50
#define UART_CLOCK              (50*MHZ)
#else
#define UART_CLOCK              (40*MHZ)
#endif
#endif


#ifdef AL_CLK_CONFIG
#define MMC_CLOCK               (100*MHZ)
#else
#ifdef AL_OSC_25
#define MMC_CLOCK               (50*MHZ)
#elif defined AL_OSC_33
#define MMC_CLOCK               (66*MHZ)
#elif defined AL_OSC_50
#define MMC_CLOCK               (100*MHZ)
#else
#define MMC_CLOCK               (10*MHZ)
#endif
#endif


/* drivers which enabled by user, generated by FD automatically.*/
#define HAVE_QSPIPS_DRIVER
#define QSPIPS_ENABLE

#define QSPI_CLOCK       (100 * MHZ)
#define QSPI_IO_FREQ     (50 * MHZ)

#define HAVE_ADCPS_DRIVER
#define ADCPS_ENABLE

#define HAVE_CANPS_DRIVER
#define CAN0PS_ENABLE
#define CAN1PS_ENABLE

#define HAVE_DMACAHBPS_DRIVER
#define DMACAHBPS_ENABLE

#define HAVE_GPIOPS_DRIVER
#define GPIOPS_ENABLE

#define HAVE_IICPS_DRIVER
#define I2C0PS_ENABLE
#define I2C1PS_ENABLE

#define I2C_CLOCK  (40 * MHZ)
#define I2C0_RATE  (100 * KHZ)
#define I2C1_RATE  (100 * KHZ)

#define HAVE_MMCPS_DRIVER
#define MMC0PS_ENABLE
#define MMC1PS_ENABLE

#define MMC0_IO_FREQ  (50 * MHZ)
#define MMC1_IO_FREQ  (50 * MHZ)

#define HAVE_MPUPS_DRIVER
#define MPUPS_ENABLE

#define HAVE_SMCPS_DRIVER
#define SMCPS_ENABLE

#define HAVE_SPIPS_DRIVER
#define SPI0PS_ENABLE
#define SPI1PS_ENABLE

#define SPI0_IO_FREQ  (5 *MHZ)
#define SPI1_IO_FREQ  (5 *MHZ)

#define HAVE_UARTPS_DRIVER
#define UART0PS_ENABLE
#define UART1PS_ENABLE

#define HAVE_GBEPS_DRIVER
#define GBE0PS_ENABLE
#define GBE1PS_ENABLE

#define HAVE_PMU_DRIVER
#define PMU_ENABLE

#define HAVE_WDTPS_DRIVER
#define WDT0PS_ENABLE
#define WDT1PS_ENABLE

#define HAVE_TCPS_DRIVER
#define TC0PS_ENABLE
#define TC1PS_ENABLE

#define HAVE_IPC_DRIVER
#define IPC_ENABLE

#define HAVE_DMAPS_DRIVER
#define DMAPS_ENABLE

#define HAVE_USBPS_DRIVER
#define USB0PS_ENABLE
#define USB1PS_ENABLE

#define GBE_DEVICE_ID (0)

#define GBE0_PTP_CLOCK (100*MHz)
#define GBE1_PTP_CLOCK (100*MHz)


/**
 * @desc  : init soc platform according to user configuration
 * @return {int} status code of platform init
 */
int Soc_PlatInit();
int Soc_PsPlInit();
int Soc_PlatGetDeviceVersion();

/* debug info */
#ifndef MMC_CLOCK
#define MMC_CLOCK              (100*MHz)
#endif
#ifndef TC_CLOCK
#define TC_CLOCK              (200*MHz)
#endif
#ifndef WDT_CLOCK
#define WDT_CLOCK              (16666667)
#endif

#ifndef SPI_CLOCK
#define SPI_CLOCK              (200*MHz)
#endif

#ifdef __cplusplus
}
#endif

#endif /* AL_SOC_BOARD_INIT_H */
